-- Schools & jobs seed (work/study catalog), keyed to move_destinations.
-- Idempotent — safe to re-run. Requires the base tables from
-- db/migrations/20260629_move_work_study.sql and the residency_pathway
-- column from db/migrations/20260714_schools_residency.sql.

-- Schools
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('lis-sch1', 'lisbon', 'Nova School of Business & Economics', 'MSc in Management', 'Master''s', 'Student visa (D4) eligible', '€50 application fee', 'D4 student visa can convert to a work residency permit (D2/D3); generally leads to permanent residency after 5 years of legal residence.', 0) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('mex-sch1', 'mexicocity', 'Tecnológico de Monterrey', 'MBA, CDMX campus', 'Master''s', 'Student visa eligible', '$80 application fee', 'Student visa can convert to a Temporary Resident work visa with a local job offer; typically leads to Permanent Residency after around 4 years.', 1) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('bkk-sch1', 'bangkok', 'Chulalongkorn University', 'International MBA', 'Master''s', 'Non-Immigrant ED visa eligible', '฿1,500 application fee', 'No automatic post-study route — graduates generally need to switch to a Non-B work visa with a Thai employer; permanent residency is quota-limited and uncommon.', 2) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('tbs-sch1', 'tbilisi', 'Free University of Tbilisi', 'BA in International Relations', 'Bachelor''s', 'Study residence permit eligible', '$30 application fee', 'Study residence permit can convert to a work residence permit; Georgia offers one of the more accessible long-term residency tracks in the region.', 3) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('ber-sch1', 'berlin', 'Technical University of Berlin', 'MSc in Computer Science', 'Master''s', 'Student visa eligible', '€75 application fee', '18-month post-study job-seeker visa after graduation; once employed, the EU Blue Card route can lead to permanent settlement in as little as 21-33 months.', 4) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('bue-sch1', 'buenosaires', 'Universidad de Buenos Aires', 'MA in Latin American Studies', 'Master''s', 'Student visa eligible', '$40 application fee', 'Student visa can transition to temporary residency with a job or income; typically leads to permanent residency after about 2 years of legal residence.', 5) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('tyo-sch1', 'tokyo', 'Waseda University', 'MA in International Studies', 'Master''s', 'Student visa (ryugaku) eligible', '¥9,800 application fee', 'Graduates can switch to a job-hunting "Designated Activities" visa for up to a year, then a work visa; permanent residency generally requires 5-10 years depending on points earned.', 6) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('cpt-sch1', 'capetown', 'University of Cape Town', 'MCom in Finance', 'Master''s', 'Study visa eligible', 'R850 application fee', 'Study visa can convert to a general or critical-skills work visa; permanent residency is typically available after about 5 years on a qualifying work visa.', 7) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('dxb-sch1', 'dubai', 'American University in Dubai', 'MBA', 'Master''s', 'Student visa eligible', 'AED 500 application fee', 'No direct citizenship/PR route — graduates usually move to employer-sponsored work residency; standout students may qualify for Golden Visa consideration.', 8) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('yyz-sch1', 'toronto', 'University of Toronto', 'Master of Information', 'Master''s', 'Study permit eligible', 'CAD 156 application fee', 'Post-Graduation Work Permit for up to 3 years; one of the clearest pathways to Permanent Residency via Express Entry / Canadian Experience Class.', 9) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('syd-sch1', 'sydney', 'University of Sydney', 'Master of Commerce', 'Master''s', 'Student visa (subclass 500) eligible', 'AUD 125 application fee', 'Temporary Graduate visa (subclass 485) for 2-4 years after study; can lead to permanent residency through skilled-visa streams (subclass 189/190).', 10) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;
insert into move_schools (id, destination_id, institution, program, level, tag, price, residency_pathway, sort_order) values ('sin-sch1', 'singapore', 'National University of Singapore', 'Master of Computing', 'Master''s', 'Student''s Pass eligible', 'SGD 100 application fee', 'Student''s Pass holders can apply for a work pass after graduation; permanent residency is discretionary and usually requires several years of employment.', 11) on conflict (id) do update set institution = excluded.institution, program = excluded.program, level = excluded.level, tag = excluded.tag, price = excluded.price, residency_pathway = excluded.residency_pathway, sort_order = excluded.sort_order, active = true;

-- Jobs
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('lis-job1', 'lisbon', 'Lisboa Software Collective', 'Backend Engineer', 'Tech', 'Visa sponsorship (D2 work visa)', '€32k–48k/yr', 0) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('mex-job1', 'mexicocity', 'CDMX FinTech Studio', 'Product Manager', 'FinTech', 'Temporary resident work permit sponsor', '$1.8k–2.6k/mo', 1) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('bkk-job1', 'bangkok', 'Bangkok Digital Works', 'UX Designer', 'Tech', 'Non-Immigrant B work-permit sponsor', '฿45k–70k/mo', 2) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('tbs-job1', 'tbilisi', 'Tbilisi Tech Yard', 'Full-Stack Developer', 'Tech', 'Work-based residence permit sponsor', '$1.2k–2k/mo', 3) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('ber-job1', 'berlin', 'Berlin Mobility Labs', 'Data Engineer', 'Tech', 'EU Blue Card sponsor', '€55k–75k/yr', 4) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('bue-job1', 'buenosaires', 'Buenos Aires Devshop', 'Software Engineer', 'Tech', 'Work visa sponsor', '$1.5k–2.4k/mo', 5) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('tyo-job1', 'tokyo', 'Tokyo Robotics Studio', 'Mechanical Engineer', 'Robotics', 'Engineer/Specialist visa sponsor', '¥4.5M–6.5M/yr', 6) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('cpt-job1', 'capetown', 'Cape Town Cloud Collective', 'Cloud Engineer', 'Tech', 'Critical skills work visa sponsor', 'R420k–650k/yr', 7) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('dxb-job1', 'dubai', 'Dubai Logistics Exchange', 'Operations Manager', 'Logistics', 'Employer-sponsored work visa', 'AED 15k–22k/mo', 8) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('yyz-job1', 'toronto', 'Toronto Fintech Forge', 'Software Engineer', 'FinTech', 'LMIA-backed work permit sponsor', 'CAD 75k–100k/yr', 9) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('syd-job1', 'sydney', 'Sydney Harbour Analytics', 'Data Analyst', 'Tech', 'Skilled employer-sponsored visa (482)', 'AUD 85k–110k/yr', 10) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
insert into move_jobs (id, destination_id, company, role, industry, tag, price, sort_order) values ('sin-job1', 'singapore', 'Singapore Cloud Bridge', 'Software Engineer', 'Tech', 'Employment Pass sponsor', 'SGD 5k–7k/mo', 11) on conflict (id) do update set company = excluded.company, role = excluded.role, industry = excluded.industry, tag = excluded.tag, price = excluded.price, sort_order = excluded.sort_order, active = true;
