import type {
  AgentProfile,
  CityMarket,
  OpportunityRow,
  PropertyListing,
  RevenueStream,
  Testimonial,
} from "@/lib/property/types"

export const seedCities: CityMarket[] = [
  {
    id: "c_lagos",
    slug: "lagos",
    name: "Lagos",
    country: "Nigeria",
    flagEmoji: "🇳🇬",
    status: "active",
    avgRentUsd: 18000,
    avgBuyUsd: 220000,
    securityScore: 74,
    commuteScore: 63,
    lifestyleScore: 81,
    topSectors: ["Finance", "Tech", "FMCG"],
    latitude: 6.5244,
    longitude: 3.3792,
  },
  {
    id: "c_abuja",
    slug: "abuja",
    name: "Abuja",
    country: "Nigeria",
    flagEmoji: "🇳🇬",
    status: "active",
    avgRentUsd: 15000,
    avgBuyUsd: 190000,
    securityScore: 79,
    commuteScore: 72,
    lifestyleScore: 75,
    topSectors: ["Public Sector", "NGO", "Legal"],
    latitude: 9.0765,
    longitude: 7.3986,
  },
  {
    id: "c_port_harcourt",
    slug: "port-harcourt",
    name: "Port Harcourt",
    country: "Nigeria",
    flagEmoji: "🇳🇬",
    status: "active",
    avgRentUsd: 12000,
    avgBuyUsd: 140000,
    securityScore: 70,
    commuteScore: 68,
    lifestyleScore: 69,
    topSectors: ["Energy", "Logistics", "Marine"],
    latitude: 4.8156,
    longitude: 7.0498,
  },
  {
    id: "c_accra",
    slug: "accra",
    name: "Accra",
    country: "Ghana",
    flagEmoji: "🇬🇭",
    status: "active",
    avgRentUsd: 14000,
    avgBuyUsd: 160000,
    securityScore: 76,
    commuteScore: 71,
    lifestyleScore: 78,
    topSectors: ["Trade", "Consumer", "Consulting"],
    latitude: 5.6037,
    longitude: -0.187,
  },
  {
    id: "c_nairobi",
    slug: "nairobi",
    name: "Nairobi",
    country: "Kenya",
    flagEmoji: "🇰🇪",
    status: "active",
    avgRentUsd: 13000,
    avgBuyUsd: 170000,
    securityScore: 72,
    commuteScore: 67,
    lifestyleScore: 77,
    topSectors: ["Fintech", "NGO", "Agritech"],
    latitude: -1.2921,
    longitude: 36.8219,
  },
  {
    id: "c_johannesburg",
    slug: "johannesburg",
    name: "Johannesburg",
    country: "South Africa",
    flagEmoji: "🇿🇦",
    status: "coming_soon",
    avgRentUsd: 16000,
    avgBuyUsd: 210000,
    securityScore: 68,
    commuteScore: 70,
    lifestyleScore: 80,
    topSectors: ["Finance", "Mining", "Retail"],
    latitude: -26.2041,
    longitude: 28.0473,
  },
  {
    id: "c_kigali",
    slug: "kigali",
    name: "Kigali",
    country: "Rwanda",
    flagEmoji: "🇷🇼",
    status: "expanding",
    avgRentUsd: 11000,
    avgBuyUsd: 130000,
    securityScore: 85,
    commuteScore: 80,
    lifestyleScore: 73,
    topSectors: ["Services", "Tech", "Hospitality"],
    latitude: -1.9441,
    longitude: 30.0619,
  },
]

export const seedListings: PropertyListing[] = [
  {
    id: "p1",
    title: "Move-in Ready 3-Bed Apartment",
    citySlug: "lagos",
    country: "Nigeria",
    neighborhood: "Ikoyi",
    type: "rent",
    priceUsd: 22000,
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 170,
    verified: true,
    moveInReady: true,
    schoolsNearby: 6,
    commuteMinutes: 24,
    description: "Modern serviced apartment with 24/7 power and secure access.",
    images: ["https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=1200&q=80"],
    agentId: "a1",
  },
  {
    id: "p2",
    title: "Family 4-Bed Duplex",
    citySlug: "abuja",
    country: "Nigeria",
    neighborhood: "Maitama",
    type: "buy",
    priceUsd: 310000,
    bedrooms: 4,
    bathrooms: 5,
    areaSqm: 340,
    verified: true,
    moveInReady: false,
    schoolsNearby: 5,
    commuteMinutes: 18,
    description: "Quiet estate duplex with green area and private parking.",
    images: ["https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80"],
    agentId: "a2",
  },
  {
    id: "p3",
    title: "Executive 2-Bed Apartment",
    citySlug: "accra",
    country: "Ghana",
    neighborhood: "Airport Residential",
    type: "rent",
    priceUsd: 17000,
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 120,
    verified: true,
    moveInReady: true,
    schoolsNearby: 4,
    commuteMinutes: 20,
    description: "Ideal for returning diaspora with flexible furnishing package.",
    images: ["https://images.unsplash.com/photo-1494526585095-c41746248156?w=1200&q=80"],
    agentId: "a3",
  },
  {
    id: "p4",
    title: "Commercial Office Floor",
    citySlug: "nairobi",
    country: "Kenya",
    neighborhood: "Westlands",
    type: "commercial",
    priceUsd: 88000,
    bedrooms: 0,
    bathrooms: 4,
    areaSqm: 420,
    verified: true,
    moveInReady: true,
    schoolsNearby: 0,
    commuteMinutes: 16,
    description: "Plug-and-play office floor for teams relocating into Nairobi.",
    images: ["https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1200&q=80"],
    agentId: "a4",
  },
  {
    id: "p5",
    title: "Waterfront 3-Bed Apartment",
    citySlug: "port-harcourt",
    country: "Nigeria",
    neighborhood: "Old GRA",
    type: "rent",
    priceUsd: 14500,
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 165,
    verified: true,
    moveInReady: true,
    schoolsNearby: 3,
    commuteMinutes: 22,
    description: "Corporate-friendly housing near major logistics and marine corridors.",
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80"],
    agentId: "a1",
  },
  {
    id: "p6",
    title: "City View Penthouse",
    citySlug: "lagos",
    country: "Nigeria",
    neighborhood: "Victoria Island",
    type: "buy",
    priceUsd: 460000,
    bedrooms: 4,
    bathrooms: 5,
    areaSqm: 370,
    verified: true,
    moveInReady: false,
    schoolsNearby: 7,
    commuteMinutes: 19,
    description: "Premium city penthouse suited for executive relocation.",
    images: ["https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80"],
    agentId: "a2",
  },
]

export const seedAgents: AgentProfile[] = [
  {
    id: "a1",
    name: "Amaka Ibe",
    company: "CityBridge Realty",
    cityCoverage: ["lagos", "port-harcourt"],
    rating: 4.8,
    verified: true,
    transactions: 128,
    languages: ["English", "Igbo"],
  },
  {
    id: "a2",
    name: "Tunde Alao",
    company: "Prime Habitat",
    cityCoverage: ["lagos", "abuja"],
    rating: 4.7,
    verified: true,
    transactions: 202,
    languages: ["English", "Yoruba"],
  },
  {
    id: "a3",
    name: "Nana Asare",
    company: "Accra Home Desk",
    cityCoverage: ["accra"],
    rating: 4.6,
    verified: true,
    transactions: 74,
    languages: ["English", "Twi"],
  },
  {
    id: "a4",
    name: "David Mwangi",
    company: "Nairobi Move Realty",
    cityCoverage: ["nairobi"],
    rating: 4.5,
    verified: true,
    transactions: 63,
    languages: ["English", "Swahili"],
  },
]

export const seedTestimonials: Testimonial[] = [
  {
    id: "t1",
    moverType: "Domestic Mover",
    route: "Lagos → Abuja",
    outcome: "Secured verified apartment in 11 days.",
    quote: "EasyMoveZone cut out fake agents and gave me clear options fast.",
  },
  {
    id: "t2",
    moverType: "Diaspora Returnee",
    route: "London → Lagos",
    outcome: "Completed search, virtual tour, and legal review remotely.",
    quote: "I moved in one week after landing because everything was pre-vetted.",
  },
  {
    id: "t3",
    moverType: "Pan-African Professional",
    route: "Accra → Nairobi",
    outcome: "Found office + home bundle before job start date.",
    quote: "For cross-border moves, this was the first platform that felt built for me.",
  },
]

export const opportunityRows: OpportunityRow[] = [
  {
    segment: "Nigerian Domestic Movers",
    sizeVolume: "~2.5M urban relocations/year",
    whyNow: "Lagos and Abuja continue to absorb migration at scale.",
  },
  {
    segment: "Diaspora Returnees",
    sizeVolume: "300,000+ annual returnees",
    whyNow: "Homecoming and investment-driven relocation is rising.",
  },
  {
    segment: "Pan-African Professionals",
    sizeVolume: "Fast-growing intra-Africa mobility",
    whyNow: "AfCFTA and regional firms are increasing cross-border hiring.",
  },
  {
    segment: "Expats & NGO Workers",
    sizeVolume: "100,000+ active in Nigeria",
    whyNow: "Stable demand for secure, verified, move-ready rentals.",
  },
]

export const revenueStreams: RevenueStream[] = [
  {
    name: "Agent Subscriptions",
    description: "Verified agents subscribe for listing access and mover lead flow.",
  },
  {
    name: "Transaction Fees",
    description: "1–2% success fee on completed rentals and purchases.",
  },
  {
    name: "Premium Mover Plans",
    description: "Concierge support for shortlisting, documentation, and move-in setup.",
  },
  {
    name: "Developer Listings",
    description: "Featured campaigns for new-build inventory and diaspora buyers.",
  },
  {
    name: "Data & Insights",
    description: "Anonymized market intelligence for developers and institutional players.",
  },
]

