import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "plus.unsplash.com" },
      { protocol: "https", hostname: "easymovezone.s3.eu-west-3.idrivee2.com" },
      { protocol: "https", hostname: "s3.eu-west-3.idrivee2.com" },
      { protocol: "https", hostname: "*.blob.core.windows.net" },
      { protocol: "https", hostname: "br-crimson-silence-ai1l8fhm.storage.c-4.us-east-1.aws.neon.tech" },
    ],
  },
  async redirects() {
    const toHome = [
      "/purchase",
      "/properties",
      "/own",
      "/mortgage",
      "/finance",
      "/build",
      "/sell",
      "/search",
      "/vendor",
      "/landlord",
      "/individual",
      "/services",
      "/cities",
      "/plan",
      "/onboarding",
      "/relocate",
      "/marketplace",
      "/employers",
      "/driver",
      "/company",
      "/start",
      "/move",
      "/fleet",
      "/explore",
      "/settle",
      "/arrived",
      "/passport",
      "/fund",
      "/community",
      "/adviser",
      "/paths",
      "/destinations",
      "/about",
      "/pricing",
      "/connect",
      "/portal",
      "/corporate",
      "/dashboard",
      "/index",
    ]

    const homeRedirects = toHome.flatMap((source) => [
      { source, destination: "/", permanent: true },
      { source: `${source}/:path*`, destination: "/", permanent: true },
    ])

    return [
      ...homeRedirects,
      { source: "/profile/driver", destination: "/profile", permanent: true },
      { source: "/profile/company", destination: "/profile", permanent: true },
      { source: "/legal/independent-contractor", destination: "/legal/terms", permanent: true },
      { source: "/can-i-move", destination: "/easymovescore", permanent: true },
      { source: "/can-i-move/:path*", destination: "/easymovescore", permanent: true },
      { source: "/career-lab", destination: "/easymovescore", permanent: true },
      { source: "/career-lab/:path*", destination: "/easymovescore", permanent: true },
      { source: "/assessments", destination: "/work-simulation", permanent: true },
      { source: "/assessments/:path*", destination: "/work-simulation", permanent: true },
      { source: "/path", destination: "/easymovescore", permanent: true },
      { source: "/path/:path*", destination: "/easymovescore", permanent: true },
      { source: "/practice", destination: "/work-simulation", permanent: true },
      { source: "/practice/:path*", destination: "/work-simulation", permanent: true },
      { source: "/app/:path*", destination: "/", permanent: true },
      { source: "/corp/:path*", destination: "/", permanent: true },
      { source: "/signup", destination: "/auth?mode=signup", permanent: false },
      { source: "/admin/kyc", destination: "/admin", permanent: true },
      { source: "/admin/cashouts", destination: "/admin", permanent: true },
      { source: "/admin/disputes", destination: "/admin", permanent: true },
      { source: "/admin/bookings", destination: "/admin", permanent: true },
      { source: "/admin/catalog", destination: "/admin", permanent: true },
      { source: "/admin/guides", destination: "/admin", permanent: true },
      { source: "/admin/services", destination: "/admin", permanent: true },
      { source: "/admin/requests", destination: "/admin", permanent: true },
    ]
  },
}

export default nextConfig
