import type { NextConfig } from "next"

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      { protocol: "https", hostname: "images.unsplash.com" },
      { protocol: "https", hostname: "plus.unsplash.com" },
      { protocol: "https", hostname: "easymovezone.s3.eu-west-3.idrivee2.com" },
      { protocol: "https", hostname: "s3.eu-west-3.idrivee2.com" },
      { protocol: "https", hostname: "*.blob.core.windows.net" },
      { protocol: "https", hostname: "br-crimson-silence-ai1l8fhm.storage.c-4.us-east-1.aws.neon.tech" },
    ],
  },
  async redirects() {
    const toHome = [
      "/purchase",
      "/properties",
      "/own",
      "/mortgage",
      "/finance",
      "/build",
      "/sell",
      "/search",
      "/vendor",
      "/landlord",
      "/individual",
      "/cities",
      "/plan",
      "/onboarding",
      "/relocate",
      "/marketplace",
      "/employers",
      "/driver",
      "/company",
      "/start",
      "/move",
      "/fleet",
      "/explore",
      "/settle",
      "/arrived",
      "/passport",
      "/fund",
      "/community",
      "/adviser",
      "/paths",
      "/destinations",
      "/about",
      "/pricing",
      "/connect",
      "/portal",
      "/corporate",
      "/dashboard",
      "/index",
    ]

    const homeRedirects = toHome.flatMap((source) => [
      { source, destination: "/", permanent: true },
      { source: `${source}/:path*`, destination: "/", permanent: true },
    ])

    return [
      ...homeRedirects,
      { source: "/profile/driver", destination: "/profile", permanent: true },
      { source: "/profile/company", destination: "/profile", permanent: true },
      { source: "/legal/independent-contractor", destination: "/legal/terms", permanent: true },
      { source: "/privacy", destination: "/legal/privacy", permanent: true },
      { source: "/terms", destination: "/legal/terms", permanent: true },
      { source: "/cookies", destination: "/legal/cookies", permanent: true },
      // News is paused; temporary so it can come back without stale permanent redirects.
      { source: "/news", destination: "/", permanent: false },
      { source: "/news/:path*", destination: "/", permanent: false },
      { source: "/admin/news", destination: "/admin/users", permanent: false },
      { source: "/admin/jobs", destination: "/admin/users", permanent: true },
      { source: "/admin/jobs/:path*", destination: "/admin/users", permanent: true },
      { source: "/admin/education", destination: "/admin/users", permanent: true },
      { source: "/admin/education/:path*", destination: "/admin/users", permanent: true },
      { source: "/app/:path*", destination: "/", permanent: true },
      { source: "/corp/:path*", destination: "/", permanent: true },
      { source: "/signup", destination: "/auth?mode=signup", permanent: false },
      { source: "/admin/kyc", destination: "/admin", permanent: true },
      { source: "/admin/cashouts", destination: "/admin", permanent: true },
      { source: "/admin/disputes", destination: "/admin", permanent: true },
      { source: "/admin/bookings", destination: "/admin", permanent: true },
      { source: "/admin/catalog", destination: "/admin", permanent: true },
      { source: "/admin/guides", destination: "/admin", permanent: true },
      { source: "/admin/services", destination: "/admin", permanent: true },
      { source: "/admin/requests", destination: "/admin", permanent: true },
      ...[
        "/jobs",
        "/sponsors",
        "/workspace",
        "/education",
        "/work-simulation",
        "/easymovescore",
        "/cv-builder",
        "/ats-friendly-cv",
        "/cover-letter-generator",
        "/career-change",
        "/ai-job-search",
        "/visa-sponsor-checker",
        "/jobs-in-uk",
        "/jobs-abroad",
        "/application-pack",
        "/specialist-support",
        "/alternatives/indeed",
        "/can-i-move",
        "/career-lab",
        "/assessments",
        "/path",
        "/practice",
      ].flatMap((source) => [
        { source, destination: "/", permanent: true },
        { source: `${source}/:path*`, destination: "/", permanent: true },
      ]),
    ]
  },
}

export default nextConfig
