import type {
  ClientEngagement,
  Corridor,
  Deliverable,
  Faq,
  IntelligenceFeedItem,
  Introduction,
  Market,
  Message,
  PartnerItem,
  PressItem,
  Report,
  Service,
  TeamMember,
  Testimonial,
  ValueCard,
} from "@/lib/platform/types"

export const seedMarkets: Market[] = [
  {
    id: "m_ng",
    slug: "nigeria",
    name: "Nigeria",
    countryCode: "NG",
    flagEmoji: "🇳🇬",
    region: "West Africa",
    status: "active",
    gdp: "$477B",
    population: "220M",
    businessEnvironmentScore: 76,
    easeOfDoingBusinessRank: 131,
    topSectors: ["Fintech", "FMCG", "Logistics"],
    regulatoryNotes: "CAC incorporation and sector licenses required for most foreign entities.",
    latitude: 9.082,
    longitude: 8.6753,
  },
  {
    id: "m_gh",
    slug: "ghana",
    name: "Ghana",
    countryCode: "GH",
    flagEmoji: "🇬🇭",
    region: "West Africa",
    status: "active",
    gdp: "$76B",
    population: "34M",
    businessEnvironmentScore: 72,
    easeOfDoingBusinessRank: 118,
    topSectors: ["Agriculture", "Consumer", "Trade"],
    regulatoryNotes: "GIPC registration is central for most non-local ownership structures.",
    latitude: 7.9465,
    longitude: -1.0232,
  },
  {
    id: "m_ke",
    slug: "kenya",
    name: "Kenya",
    countryCode: "KE",
    flagEmoji: "🇰🇪",
    region: "East Africa",
    status: "active",
    gdp: "$119B",
    population: "56M",
    businessEnvironmentScore: 74,
    easeOfDoingBusinessRank: 56,
    topSectors: ["Fintech", "Agritech", "Retail"],
    regulatoryNotes: "Central Bank and Data Protection compliance are key for digital operators.",
    latitude: -0.0236,
    longitude: 37.9062,
  },
  {
    id: "m_gb",
    slug: "united-kingdom",
    name: "United Kingdom",
    countryCode: "GB",
    flagEmoji: "🇬🇧",
    region: "Europe",
    status: "active",
    gdp: "$3.1T",
    population: "68M",
    businessEnvironmentScore: 84,
    easeOfDoingBusinessRank: 8,
    topSectors: ["Retail", "Professional Services", "Creative"],
    regulatoryNotes: "FCA, HMRC, and import standards vary by sector; pre-entry structuring is critical.",
    latitude: 55.3781,
    longitude: -3.436,
  },
  {
    id: "m_ae",
    slug: "uae",
    name: "UAE",
    countryCode: "AE",
    flagEmoji: "🇦🇪",
    region: "Middle East",
    status: "active",
    gdp: "$507B",
    population: "10M",
    businessEnvironmentScore: 83,
    easeOfDoingBusinessRank: 16,
    topSectors: ["Trade", "Luxury", "Logistics"],
    regulatoryNotes: "Free-zone and mainland licensing paths differ materially in cost and scope.",
    latitude: 23.4241,
    longitude: 53.8478,
  },
  {
    id: "m_us",
    slug: "united-states",
    name: "United States",
    countryCode: "US",
    flagEmoji: "🇺🇸",
    region: "North America",
    status: "active",
    gdp: "$29T",
    population: "334M",
    businessEnvironmentScore: 87,
    easeOfDoingBusinessRank: 6,
    topSectors: ["Enterprise", "Diaspora Retail", "Media"],
    regulatoryNotes: "State-by-state compliance and federal tax structuring determine speed to launch.",
    latitude: 39.8283,
    longitude: -98.5795,
  },
  {
    id: "m_za",
    slug: "south-africa",
    name: "South Africa",
    countryCode: "ZA",
    flagEmoji: "🇿🇦",
    region: "Southern Africa",
    status: "coming_soon",
    gdp: "$380B",
    population: "61M",
    businessEnvironmentScore: 69,
    easeOfDoingBusinessRank: 84,
    topSectors: ["Finance", "Mining", "Retail"],
    regulatoryNotes: "B-BBEE structuring has direct implications on partnership strategy.",
    latitude: -30.5595,
    longitude: 22.9375,
  },
  {
    id: "m_sn",
    slug: "senegal",
    name: "Senegal",
    countryCode: "SN",
    flagEmoji: "🇸🇳",
    region: "West Africa",
    status: "monitoring",
    gdp: "$31B",
    population: "18M",
    businessEnvironmentScore: 67,
    easeOfDoingBusinessRank: 123,
    topSectors: ["Energy", "Trade", "Logistics"],
    regulatoryNotes: "OHADA legal framework and francophone localization are key entry variables.",
    latitude: 14.4974,
    longitude: -14.4524,
  },
]

export const seedCorridors: Corridor[] = [
  { id: "c1", originMarketId: "m_gb", destinationMarketId: "m_ng", sector: "Fintech", activeClientCount: 14, status: "active" },
  { id: "c2", originMarketId: "m_us", destinationMarketId: "m_ke", sector: "Consumer Tech", activeClientCount: 9, status: "active" },
  { id: "c3", originMarketId: "m_ae", destinationMarketId: "m_gh", sector: "Trade", activeClientCount: 7, status: "active" },
  { id: "c4", originMarketId: "m_ng", destinationMarketId: "m_gb", sector: "Food & Beverage", activeClientCount: 11, status: "active" },
  { id: "c5", originMarketId: "m_gh", destinationMarketId: "m_ae", sector: "Agriculture", activeClientCount: 6, status: "active" },
  { id: "c6", originMarketId: "m_ke", destinationMarketId: "m_us", sector: "Creative", activeClientCount: 5, status: "active" },
]

export const seedServices: Service[] = [
  {
    id: "s_in_1",
    direction: "inbound",
    name: "Market Intelligence Report",
    description: "Custom market report with demand, regulation, competitor mapping, and risk.",
    clientReceives: "Actionable report, confidence score, launch opportunity map.",
    emzExecution: "Primary and secondary research plus local expert validation.",
    timeline: "2-3 weeks",
    priceMin: 2000,
    priceMax: 4500,
  },
  {
    id: "s_in_2",
    direction: "inbound",
    name: "Ground Truth Introductions",
    description: "Vetted introductions to real distributors, partners, and first anchor customers.",
    clientReceives: "Warm intros with context packs and risk filters.",
    emzExecution: "Partner vetting, fit scoring, and meeting coordination.",
    timeline: "2-4 weeks",
    priceMin: 1500,
    priceMax: 7000,
  },
  {
    id: "s_in_3",
    direction: "inbound",
    name: "Full Market Entry Package",
    description: "End-to-end launch coordination from setup through first-market operations.",
    clientReceives: "Entry blueprint, implementation owner, launch oversight.",
    emzExecution: "Entity setup coordination, hiring support, and operational rollout.",
    timeline: "6-12 weeks",
    priceMin: 15000,
    priceMax: 45000,
    featured: true,
  },
  {
    id: "s_in_4",
    direction: "inbound",
    name: "Monthly Intelligence Retainer",
    description: "Monthly intelligence updates for active market operators.",
    clientReceives: "Alerts, opportunity briefs, and monthly advisor call.",
    emzExecution: "Continuous monitoring and strategic recommendations.",
    timeline: "Monthly",
    priceMin: 1500,
    priceMax: 5000,
  },
  {
    id: "s_in_5",
    direction: "inbound",
    name: "Regulatory Compliance Support",
    description: "Compliance readiness support for sector-specific operations.",
    clientReceives: "Regulatory checklist, filing roadmap, and compliance cadence.",
    emzExecution: "Compliance coordination with specialist legal/accounting partners.",
    timeline: "3-8 weeks",
    priceMin: 3500,
    priceMax: 14000,
  },
  {
    id: "s_in_6",
    direction: "inbound",
    name: "Launch Event Coordination",
    description: "Local market launch orchestration for visibility and traction.",
    clientReceives: "Launch plan, media list, partner guest strategy.",
    emzExecution: "Event planning, PR partner coordination, and post-event follow-through.",
    timeline: "2-5 weeks",
    priceMin: 2500,
    priceMax: 12000,
  },
  {
    id: "s_out_1",
    direction: "outbound",
    name: "Export Readiness Assessment",
    description: "Diagnose whether your business is operationally ready for cross-border growth.",
    clientReceives: "Readiness score with exact capability gaps.",
    emzExecution: "Product, compliance, and distribution readiness review.",
    timeline: "1-2 weeks",
    priceMin: 1200,
    priceMax: 3500,
  },
  {
    id: "s_out_2",
    direction: "outbound",
    name: "Market Selection Strategy",
    description: "Choose the right first market based on fit, regulation, and speed to revenue.",
    clientReceives: "Prioritized market shortlist with scorecards.",
    emzExecution: "Comparative opportunity analysis and sequencing advice.",
    timeline: "2-3 weeks",
    priceMin: 1800,
    priceMax: 6000,
  },
  {
    id: "s_out_3",
    direction: "outbound",
    name: "Distribution Partnership Setup",
    description: "Source and qualify importers, distributors, and channel partners abroad.",
    clientReceives: "Partner pipeline and conversion support.",
    emzExecution: "Partner sourcing, diligence, and intro management.",
    timeline: "3-6 weeks",
    priceMin: 4000,
    priceMax: 16000,
    featured: true,
  },
  {
    id: "s_out_4",
    direction: "outbound",
    name: "Brand Localization Package",
    description: "Adapt your brand for cultural fit and buyer conversion in target markets.",
    clientReceives: "Localized positioning and go-to-market message stack.",
    emzExecution: "Brand adaptation strategy with local creative input.",
    timeline: "2-5 weeks",
    priceMin: 2200,
    priceMax: 9000,
  },
  {
    id: "s_out_5",
    direction: "outbound",
    name: "Global Expansion Retainer",
    description: "Ongoing expansion co-pilot for sustained global growth.",
    clientReceives: "Monthly planning, execution support, and partner pipeline.",
    emzExecution: "Cross-market operating support with growth reviews.",
    timeline: "Monthly",
    priceMin: 2500,
    priceMax: 9000,
  },
  {
    id: "s_out_6",
    direction: "outbound",
    name: "Investor Introduction Service",
    description: "Prepare and introduce expansion-ready businesses to aligned capital partners.",
    clientReceives: "Investor narrative prep and curated intro shortlist.",
    emzExecution: "Readiness filtering, matching, and intro coordination.",
    timeline: "4-8 weeks",
    priceMin: 5000,
    priceMax: 25000,
  },
]

export const seedFaqs: Faq[] = [
  { id: "f1", question: "How long does a typical market entry engagement take?", answer: "Most entry engagements run 6-12 weeks from intelligence to launch preparation.", orderIndex: 1 },
  { id: "f2", question: "Do you work with startups or only established companies?", answer: "We support both, but package fit depends on readiness, timeline, and budget.", orderIndex: 2 },
  { id: "f3", question: "Can engagements start with intelligence only?", answer: "Yes. Many clients start with a focused report before full execution support.", orderIndex: 3 },
  { id: "f4", question: "How do you handle confidentiality?", answer: "All engagements are covered by confidentiality terms and controlled data access.", orderIndex: 4 },
  { id: "f5", question: "Do you guarantee market success?", answer: "No advisor can guarantee outcomes; we reduce risk and increase decision quality.", orderIndex: 5 },
  { id: "f6", question: "What happens after the project ends?", answer: "Clients can continue with retainers for ongoing intelligence and opportunity monitoring.", orderIndex: 6 },
  { id: "f7", question: "How are payments structured?", answer: "Depending on package: one-time fees, monthly retainers, or milestone-based project payments.", orderIndex: 7 },
  { id: "f8", question: "Can you support more than one market at once?", answer: "Yes, with phased sequencing so execution quality remains high.", orderIndex: 8 },
]

export const seedReports: Report[] = [
  {
    id: "r1",
    title: "Consumer Tech Market Entry Guide 2026",
    marketId: "m_ng",
    sector: "Tech",
    direction: "inbound",
    summary: "Regulatory environment and channel strategy for tech businesses entering Lagos.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "Lagos remains high-growth but compliance sequencing is the main determinant of speed.",
    price: 2400,
    publishDate: "2026-02-14",
    lastUpdatedDate: "2026-03-01",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/consumer-tech-market-entry-guide-2026.pdf",
    purchaseCount: 68,
    tags: ["Regulatory", "Channels", "Consumer"],
  },
  {
    id: "r2",
    title: "African Food & Beverage Export Playbook",
    marketId: "m_gb",
    sector: "FMCG",
    direction: "outbound",
    summary: "UK buyer pathways and compliance for African F&B brands.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "Buyer trust rises when compliance and diaspora strategy are sequenced, not parallelized.",
    price: 2200,
    publishDate: "2026-01-20",
    lastUpdatedDate: "2026-02-17",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/african-food-beverage-export-playbook.pdf",
    purchaseCount: 52,
    tags: ["Retail", "Import", "Diaspora"],
  },
  {
    id: "r3",
    title: "African SME Trade Corridor Report",
    marketId: "m_ae",
    sector: "Trade",
    direction: "outbound",
    summary: "Licensing, free-zone options, and route to first distributor in Dubai.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "License-path misalignment is the #1 avoidable delay for new UAE entrants.",
    price: 2800,
    publishDate: "2025-12-12",
    lastUpdatedDate: "2026-01-11",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/african-sme-trade-corridor-report.pdf",
    purchaseCount: 31,
    tags: ["Free Zone", "Banking", "Distribution"],
  },
  {
    id: "r4",
    title: "Fintech & Mobile Money Landscape 2026",
    marketId: "m_ke",
    sector: "Finance",
    direction: "inbound",
    summary: "Competitive and regulatory map for fintech operators in Nairobi.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "Payment rails and regulator posture make partnership strategy decisive in Kenya.",
    price: 2600,
    publishDate: "2026-02-08",
    lastUpdatedDate: "2026-03-04",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/fintech-mobile-money-landscape-2026.pdf",
    purchaseCount: 47,
    tags: ["Payments", "RegTech", "Partnerships"],
  },
  {
    id: "r5",
    title: "Retail & Distribution Network Guide",
    marketId: "m_gh",
    sector: "Consumer",
    direction: "inbound",
    summary: "Import procedures and last-mile channel mapping in Accra.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "Distributor incentives and territory design shape margin outcomes in Ghana.",
    price: 1900,
    publishDate: "2025-11-05",
    lastUpdatedDate: "2025-12-18",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/retail-distribution-network-guide.pdf",
    purchaseCount: 40,
    tags: ["Retail", "Import", "Territory"],
  },
  {
    id: "r6",
    title: "African Creative Industries Export Guide",
    marketId: "m_us",
    sector: "Creative Industries",
    direction: "outbound",
    summary: "US market pathways for African creative brands and studios.",
    fullContent: "Full report content placeholder.",
    previewExcerpt: "Rights structure and platform strategy materially impact monetization velocity.",
    price: 3200,
    publishDate: "2026-01-30",
    lastUpdatedDate: "2026-02-22",
    author: "EMZ Intelligence Desk",
    downloadUrl: "/reports/african-creative-industries-export-guide.pdf",
    purchaseCount: 25,
    tags: ["IP", "Platform", "Diaspora"],
  },
]

export const seedTestimonials: Testimonial[] = [
  {
    id: "t1",
    clientType: "UK-based SaaS firm",
    corridorId: "c1",
    outcome: "Launched in Lagos with two distributor partnerships in 90 days.",
    quote: "EasyMoveZone compressed our learning curve by months and prevented expensive errors.",
  },
  {
    id: "t2",
    clientType: "Nigerian FMCG exporter",
    corridorId: "c4",
    outcome: "Secured first UK retail pilot and repeat orders within one quarter.",
    quote: "The corridor strategy and introductions moved us from interest to shelf presence fast.",
  },
  {
    id: "t3",
    clientType: "Kenyan fintech operator",
    corridorId: "c6",
    outcome: "Entered US partnership pipeline with compliant positioning.",
    quote: "We finally knew who to speak with, when, and with what story.",
  },
]

export const seedTeam: TeamMember[] = [
  {
    id: "tm1",
    section: "team",
    name: "Amara Okafor",
    title: "Head of Market Intelligence",
    bio: "Leads corridor intelligence programs across West and East Africa.",
    photoUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=320&q=80",
    markets: ["Nigeria", "Ghana", "Kenya"],
    linkedinUrl: "https://linkedin.com",
  },
  {
    id: "tm2",
    section: "team",
    name: "David Mensah",
    title: "Global Expansion Lead",
    bio: "Builds outbound market pathways for African SMEs scaling internationally.",
    photoUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=320&q=80",
    markets: ["United Kingdom", "UAE", "United States"],
    linkedinUrl: "https://linkedin.com",
  },
  {
    id: "ad1",
    section: "advisor",
    name: "Lara Obi",
    title: "Regulatory Advisor",
    bio: "Supports cross-border regulatory readiness and risk controls.",
    photoUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=320&q=80",
    markets: ["Nigeria", "United Kingdom"],
    linkedinUrl: "https://linkedin.com",
  },
]

export const seedValues: ValueCard[] = [
  { id: "v1", orderIndex: 1, title: "Truth Before Comfort", description: "We prioritize signal over sugar-coating. Clients deserve clarity, not optimism theater." },
  { id: "v2", orderIndex: 2, title: "Movement Is Mission", description: "Markets move fast. We help clients move with timing and confidence." },
  { id: "v3", orderIndex: 3, title: "Africa Is Opportunity", description: "We reject risk-only narratives and surface practical pathways to growth." },
  { id: "v4", orderIndex: 4, title: "Corridor Runs Both Ways", description: "Inbound and outbound growth are equally strategic and equally important." },
  { id: "v5", orderIndex: 5, title: "Relationships Over Transactions", description: "Our reputation sits inside every introduction we make and every partner we endorse." },
  { id: "v6", orderIndex: 6, title: "Living Intelligence", description: "Markets evolve monthly, so our intelligence is designed to evolve with them." },
]

export const seedPress: PressItem[] = [
  { id: "p1", name: "BusinessDay", logoUrl: "https://dummyimage.com/160x56/eee/222&text=BusinessDay", articleUrl: "#" },
  { id: "p2", name: "TechCabal", logoUrl: "https://dummyimage.com/160x56/eee/222&text=TechCabal", articleUrl: "#" },
  { id: "p3", name: "The Guardian", logoUrl: "https://dummyimage.com/160x56/eee/222&text=Guardian", articleUrl: "#" },
]

export const seedPartners: PartnerItem[] = [
  { id: "pa1", name: "Apex Legal", logoUrl: "https://dummyimage.com/160x56/f5f0e8/222&text=Apex+Legal", country: "Nigeria", websiteUrl: "#" },
  { id: "pa2", name: "Bridge Accountants", logoUrl: "https://dummyimage.com/160x56/f5f0e8/222&text=Bridge+Accounting", country: "United Kingdom", websiteUrl: "#" },
  { id: "pa3", name: "Trade Hub UAE", logoUrl: "https://dummyimage.com/160x56/f5f0e8/222&text=Trade+Hub", country: "UAE", websiteUrl: "#" },
]

export const seedClientEngagements: ClientEngagement[] = [
  {
    id: "ce1",
    userId: "demo-user",
    engagementType: "Full Market Entry",
    corridorId: "c1",
    advisorName: "Amara Okafor",
    advisorPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=320&q=80",
    phase: "Partner Qualification",
    startDate: "2026-01-18",
    contractValue: 28000,
    nextMilestone: "Distributor shortlist review - Mar 28",
  },
]

export const seedDeliverables: Deliverable[] = [
  { id: "d1", clientId: "ce1", name: "Nigeria Entry Intelligence Dossier", dueDate: "2026-02-01", status: "approved", fileUrl: "#", notes: "Approved by client team." },
  { id: "d2", clientId: "ce1", name: "Regulatory Risk Matrix", dueDate: "2026-02-20", status: "delivered", fileUrl: "#", notes: "Awaiting final comments." },
  { id: "d3", clientId: "ce1", name: "Distributor Longlist + Scoring", dueDate: "2026-03-10", status: "in_progress", fileUrl: "#", notes: "8 candidates currently in pipeline." },
]

export const seedIntroductions: Introduction[] = [
  {
    id: "i1",
    clientId: "ce1",
    contactName: "Kemi Afolabi",
    company: "Prime Retail Distribution",
    introductionDate: "2026-03-01",
    purpose: "National distributor exploration",
    outcomeStatus: "meeting_scheduled",
  },
  {
    id: "i2",
    clientId: "ce1",
    contactName: "Ola Martins",
    company: "Swift Shelf Networks",
    introductionDate: "2026-03-03",
    purpose: "Urban retail pilot",
    outcomeStatus: "deal_in_progress",
  },
]

export const seedMessages: Message[] = [
  {
    id: "msg1",
    clientId: "ce1",
    senderRole: "advisor",
    content: "We uploaded the updated distributor scorecard and highlighted top 3 candidates.",
    timestamp: "2026-03-07T10:30:00Z",
    readStatus: true,
  },
  {
    id: "msg2",
    clientId: "ce1",
    senderRole: "client",
    content: "Received, we are reviewing and will share shortlist preferences tomorrow.",
    timestamp: "2026-03-07T14:12:00Z",
    readStatus: false,
  },
]

export const seedIntelligenceFeed: IntelligenceFeedItem[] = [
  {
    id: "if1",
    corridorId: "c1",
    title: "Lagos import tariff adjustment",
    content: "Revised tariff classification is likely to affect landed cost by 2-4% in your category.",
    publishedAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "if2",
    corridorId: "c1",
    title: "Distributor channel pricing movement",
    content: "Top distributor cohorts are asking for shorter payment cycles in Q2 negotiations.",
    publishedAt: "2026-03-06T13:00:00Z",
  },
]

