"use client";
import {useState} from "react";
import Image from "next/image";
import type {Move} from "@/lib/moving/model";
import {planSummary,type MoveTask} from "@/lib/moving/planner";
import s from "./MovePlanner.module.css";
export function MovePlanPanel({move,role,onUpdated}:{move:Move;role:"customer"|"crew"|"admin";onUpdated:(move:Move)=>void}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 if(!move.inventoryPlan&&!move.planTasks?.length)return null;
 const summary=planSummary(move.inventoryPlan?.items??[]);
 async function update(task:MoveTask,status:MoveTask["status"],notes:string){setBusy(true);setError("");try{const r=await fetch("/api/moves/plan",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({reference:move.reference,taskId:task.id,status,notes})});const d=await r.json();if(!r.ok)throw new Error(d.error);onUpdated(d.move);}catch(e){setError(e instanceof Error?e.message:"Could not save this step.");}finally{setBusy(false);}}
 return <section className={s.planner} aria-label="Move plan"><h3>Your move, step by step</h3><p>The team coordinates the quote, vehicle and crew. Follow packing, delivery and setup here; your responsibilities are shown alongside ours.</p>{move.inventoryPlan&&<details><summary>Item photos, sizes and handling ({move.inventoryPlan.items.length} item types)</summary><p>{summary.volumeM3} m³ from supplied sizes · {summary.missing} sizes still needed · {summary.unconfirmed} measurements awaiting confirmation.</p><div className={s.items}>{move.inventoryPlan.items.map(i=><article className={s.item} key={i.id}><h4>{i.quantity} × {i.name} · {i.room}</h4>{i.photoIndex!==null&&move.photos[i.photoIndex]&&<Image unoptimized src={move.photos[i.photoIndex]} alt={`Moving item: ${i.name}`} width={180} height={130} style={{objectFit:"cover",borderRadius:8,maxWidth:"100%"}}/>}<p>{i.dimensions?`${i.dimensions.widthCm} × ${i.dimensions.depthCm} × ${i.dimensions.heightCm} cm (width × depth × height)`:"Size needs checking"} · {i.measurementSource==="photo-estimate"?"Photo estimate":i.measurementSource==="measured"?"Customer confirmed with tape measure":i.measurementSource==="customer-entered"?"Entered; not confirmed":"Unknown"}</p><p>{[i.fragile?"Fragile":"",i.disassembly?"Furniture work needed":"",i.notes].filter(Boolean).join(" · ")}</p></article>)}</div></details>}{move.planTasks?.map(t=><div key={t.id} className={s.task} data-done={t.status==="done"}><strong>{t.status==="done"?"✓ ":""}{t.title}</strong><small>{t.owner==="customer"?"Your step":t.owner==="team"?"Our coordination team":"Your moving crew"} · {t.status==="blocked"?"Needs attention":t.status}</small>{t.notes&&<p>{t.notes}</p>}{move.status!=="cancelled"&&(role==="admin"||role===t.owner)&&<div className={s.actions}><select aria-label={`Status: ${t.title}`} value={t.status} disabled={busy} onChange={e=>void update(t,e.target.value as MoveTask["status"],t.notes)}><option value="pending">Pending</option><option value="done">Done</option><option value="blocked">Needs attention</option></select><label>Step notes<input aria-label={`Notes: ${t.title}`} defaultValue={t.notes} maxLength={500} disabled={busy} onBlur={e=>{if(e.target.value!==t.notes)void update(t,t.status,e.target.value);}}/></label></div>}</div>)}{error&&<p role="alert">{error}</p>}</section>;
}
