"use client";
import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import {MAX_MOVE_PHOTOS, ROOMS, planSummary, validDimensions, type InventoryPlan, type PlannedItem} from "@/lib/moving/planner";
import styles from "./MovePlanner.module.css";
async function compressPhoto(file: File): Promise<string> {
 if(!["image/jpeg","image/png","image/webp"].includes(file.type) || file.size>10000000) throw new Error("Choose JPG, PNG or WebP photos under 10 MB each.");
 const url=URL.createObjectURL(file);
 try {
 const image=await new Promise<HTMLImageElement>((resolve,reject)=>{const img=new window.Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error("This photo could not be opened."));img.src=url;});
 const scale=Math.min(1,1280/Math.max(image.width,image.height)); const canvas=document.createElement("canvas");canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);
 const ctx=canvas.getContext("2d");if(!ctx)throw new Error("Photo processing is unavailable.");ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0,canvas.width,canvas.height);
 for(const quality of [.82,.65,.45,.3]){const data=canvas.toDataURL("image/jpeg",quality);if(data.length<=550000)return data;}
 throw new Error("This photo is too detailed. Try a smaller photo.");
 }finally{URL.revokeObjectURL(url);}
}
export function PhotoInventoryPlanner({plan,photos,onChange,onPhotos}:{plan:InventoryPlan;photos:string[];onChange:(p:InventoryPlan)=>void;onPhotos:(p:string[])=>void}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[signIn,setSignIn]=useState(false),[replace,setReplace]=useState(false);
 const summary=planSummary(plan.items);
 const change=(items:PlannedItem[])=>onChange({...plan,items,reviewed:false});
 const patch=(id:string,value:Partial<PlannedItem>)=>change(plan.items.map(i=>i.id===id?{...i,...value}:i));
 async function upload(files:FileList|null){if(!files?.length)return;setError("");if(files.length+photos.length>MAX_MOVE_PHOTOS){setError("You can add up to 12 photos. Remove an old photo to add another.");return;}setBusy(true);try{onPhotos([...photos,...await Promise.all(Array.from(files).map(compressPhoto))]);onChange({...plan,reviewed:false});}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function analyse(){if(plan.items.length && !replace){setReplace(true);return;}setBusy(true);setError("");setSignIn(false);try{const r=await fetch("/api/moves/analyse",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({photos,references:plan.references})});const d=await r.json();if(!r.ok){setSignIn(r.status===401);throw new Error(d.error);}change(d.items);setReplace(false);if(!d.items.length)setError("No movable items were detected. Take a closer photo or add items below.");}catch(e){setError(e instanceof Error?e.message:"Could not analyse photos. Add items below.");}finally{setBusy(false);}}
 function removePhoto(index:number){onPhotos(photos.filter((_,i)=>i!==index));onChange({...plan,reviewed:false,references:plan.references.filter(r=>r.photoIndex!==index).map(r=>({...r,photoIndex:r.photoIndex>index?r.photoIndex-1:r.photoIndex})),items:plan.items.map(i=>i.photoIndex===index?{...i,photoIndex:null,...(i.measurementSource==="photo-estimate"?{dimensions:null,measurementSource:"unknown" as const}:{})}:i.photoIndex!==null && i.photoIndex>index?{...i,photoIndex:i.photoIndex-1}:i)});}
 return <div className={styles.planner}>
 <h3>Show us what needs moving</h3><p>Take clear photos of each room or large item. We can draft the list, flag fragile items and help plan packing and furniture setup.</p>
 <div className={styles.actions}><label className={styles.upload}>Upload room or item photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label><label className={styles.upload}>Take a photo<input type="file" accept="image/*" capture="environment" disabled={busy} onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label></div>
 <small>{photos.length}/12 photos. Avoid faces, documents and valuables you are not moving.</small>
 <div className={styles.photos}>{photos.map((photo,index)=><div key={photo} className={styles.photo}><Image unoptimized src={photo} alt={`Moving photo ${index+1}`} width={180} height={130}/><strong>Photo {index+1}</strong><button type="button" disabled={busy} onClick={()=>removePhoto(index)}>Remove photo</button><details><summary>Help estimate sizes (optional)</summary><p>Include an object with a known size next to the item, at a similar distance from the camera.</p><label>Reference object<input maxLength={200} placeholder="e.g. 30 cm ruler beside sofa" value={plan.references.find(r=>r.photoIndex===index)?.description??""} onChange={e=>{const existing=plan.references.find(r=>r.photoIndex===index);onChange({...plan,reviewed:false,references:[...plan.references.filter(r=>r.photoIndex!==index),{photoIndex:index,description:e.target.value,lengthCm:existing?.lengthCm??0}],items:plan.items.map(i=>i.photoIndex===index && i.measurementSource==="photo-estimate"?{...i,dimensions:null,measurementSource:"unknown"}:i)});}}/></label><label>Known length (cm)<input type="number" min={.1} max={2000} step="any" value={plan.references.find(r=>r.photoIndex===index)?.lengthCm||""} onChange={e=>{const existing=plan.references.find(r=>r.photoIndex===index);onChange({...plan,reviewed:false,references:[...plan.references.filter(r=>r.photoIndex!==index),{photoIndex:index,description:existing?.description??"",lengthCm:Number(e.target.value)}],items:plan.items.map(i=>i.photoIndex===index && i.measurementSource==="photo-estimate"?{...i,dimensions:null,measurementSource:"unknown"}:i)});}}/></label><button type="button" onClick={()=>onChange({...plan,reviewed:false,references:plan.references.filter(r=>r.photoIndex!==index),items:plan.items.map(i=>i.photoIndex===index&&i.measurementSource==="photo-estimate"?{...i,dimensions:null,measurementSource:"unknown"}:i)})}>Clear reference</button></details></div>)}</div>
 <button type="button" className={styles.primary} disabled={busy||!photos.length||plan.references.some(r=>!r.description.trim()||r.lengthCm<=0)} onClick={()=>void analyse()}>{busy?"Processing photos…":replace?"Replace current list with a new photo draft":"Create item list from photos"}</button>
 {replace&&<p>Your current list will be replaced. <button type="button" onClick={()=>setReplace(false)}>Keep current list</button></p>}
 <small>By choosing photo analysis, you send these photos to our AI provider. Review the draft for missing items. Photo sizes are estimates; use a tape measure to confirm them.</small>
 {error&&<p role="alert">{error} {signIn&&<Link href="/auth" target="_blank" rel="noreferrer">Sign in in another tab, then retry here</Link>}</p>}
 <div className={styles.items}>{plan.items.map((item,index)=><article className={styles.item} key={item.id}><h4>Item {index+1}</h4><div className={styles.fields}><label>Item name<input required maxLength={120} value={item.name} onChange={e=>patch(item.id,{name:e.target.value})}/></label><label>Room<select value={item.room} onChange={e=>patch(item.id,{room:e.target.value})}>{ROOMS.map(r=><option key={r}>{r}</option>)}</select></label><label>Quantity<input type="number" min={1} max={100} required value={item.quantity} onChange={e=>patch(item.id,{quantity:Number(e.target.value)})}/></label><label>Item photo<select value={item.photoIndex??""} onChange={e=>patch(item.id,{photoIndex:e.target.value===""?null:Number(e.target.value),...(item.measurementSource==="photo-estimate"?{dimensions:null,measurementSource:"unknown"}:{})})}><option value="">No photo</option>{photos.map((_,i)=><option key={i} value={i}>Photo {i+1}</option>)}</select></label></div><p><strong>{item.measurementSource==="photo-estimate"?"Estimated from photo — check before moving":item.measurementSource==="measured"?"Confirmed with a tape measure":item.dimensions?"Entered sizes — not yet confirmed":"Size unknown — our team will help check"}</strong></p><div className={styles.fields}>{(["widthCm","depthCm","heightCm"] as const).map(axis=><label key={axis}>{axis==="widthCm"?"Width":axis==="depthCm"?"Depth":"Height"} (cm)<input type="number" min={.1} max={2000} step="any" value={item.dimensions?.[axis]||""} onChange={e=>patch(item.id,{dimensions:{widthCm:0,depthCm:0,heightCm:0,...item.dimensions,[axis]:Number(e.target.value)},measurementSource:"customer-entered"})}/></label>)}</div><div className={styles.actions}><label><input type="checkbox" disabled={!validDimensions(item.dimensions)} checked={item.measurementSource==="measured"} onChange={e=>patch(item.id,{measurementSource:e.target.checked?"measured":"customer-entered"})}/> I checked these sizes with a tape measure</label><button type="button" onClick={()=>patch(item.id,{dimensions:null,measurementSource:"unknown"})}>Leave size for team to check</button></div><div className={styles.actions}><label><input type="checkbox" checked={item.fragile} onChange={e=>patch(item.id,{fragile:e.target.checked})}/> Fragile</label><label><input type="checkbox" checked={item.disassembly} onChange={e=>patch(item.id,{disassembly:e.target.checked})}/> Needs dismantling / reassembly</label></div><label>Handling notes<input maxLength={500} value={item.notes} onChange={e=>patch(item.id,{notes:e.target.value})} placeholder="e.g. glass top, destination bedroom"/></label><button type="button" onClick={()=>change(plan.items.filter(i=>i.id!==item.id))}>Remove item</button></article>)}</div>
 <button type="button" disabled={plan.items.length>=80||busy} onClick={()=>change([...plan.items,{id:crypto.randomUUID(),name:"",room:"Other",quantity:1,photoIndex:null,dimensions:null,measurementSource:"unknown",fragile:false,disassembly:false,notes:""}])}>+ Add an item yourself</button>
 {plan.items.length>0&&<div className={styles.summary}><strong>{plan.items.reduce((n,i)=>n+i.quantity,0)} items · {summary.volumeM3} m³ of known sizes</strong><p>{summary.missing} item types need sizes; {summary.unconfirmed} need measurement confirmation. {summary.fragile} fragile; {summary.disassembly} need furniture work.</p><p>Our team confirms the vehicle, access and packing needs before the final quote.</p><label><input type="checkbox" required checked={plan.reviewed} onChange={e=>onChange({...plan,reviewed:e.target.checked})}/> I have checked the item list and flagged anything that needs measuring.</label></div>}
 </div>;
}
