/**
 * Suitability Portal role catalog — source of truth for standard titles,
 * tools, industries, and focus areas. Run `npm run db:seed:suitability` to
 * sync into the database; the API falls back to this module if the table is empty.
 */

export const SUITABILITY_LEVELS = [
  { id: "junior", label: "Junior / Entry" },
  { id: "mid", label: "Mid-level" },
  { id: "senior", label: "Senior" },
  { id: "lead", label: "Lead / Principal" },
  { id: "executive", label: "Executive" },
] as const;

export type SuitabilityLevelId = (typeof SUITABILITY_LEVELS)[number]["id"];

export const SUITABILITY_INDUSTRIES = [
  "Technology",
  "Healthcare",
  "Finance",
  "Banking",
  "Insurance",
  "Marketing",
  "Advertising",
  "Sales",
  "Retail",
  "E-commerce",
  "Education",
  "Legal",
  "Consulting",
  "Manufacturing",
  "Logistics",
  "Construction",
  "Energy",
  "Media",
  "Entertainment",
  "Hospitality",
  "Nonprofit",
  "Government",
  "Real Estate",
  "Telecommunications",
  "Pharmaceuticals",
  "Automotive",
  "Aerospace",
  "Agriculture",
] as const;

/** Broader, clearer buckets so a large catalog stays browsable. */
export const SUITABILITY_CATEGORIES = [
  { id: "software", label: "Software Engineering" },
  { id: "it-security", label: "IT & Cybersecurity" },
  { id: "data-ai", label: "Data & AI" },
  { id: "product", label: "Product" },
  { id: "design", label: "Design & UX" },
  { id: "marketing", label: "Marketing & Growth" },
  { id: "sales", label: "Sales" },
  { id: "customer", label: "Customer Success & Support" },
  { id: "finance", label: "Finance & Accounting" },
  { id: "hr", label: "People & HR" },
  { id: "operations", label: "Operations & Supply Chain" },
  { id: "project", label: "Project & Program Management" },
  { id: "healthcare", label: "Healthcare & Clinical" },
  { id: "legal", label: "Legal & Compliance" },
  { id: "education", label: "Education & Training" },
  { id: "strategy", label: "Business & Strategy" },
  { id: "media", label: "Media & Communications" },
  { id: "hospitality", label: "Hospitality & Retail" },
  { id: "skilled", label: "Skilled Trades & Field" },
  { id: "public", label: "Public & Nonprofit" },
] as const;

export type SuitabilityRoleTemplate = {
  id: string;
  title: string;
  category: string;
  defaultIndustry: string;
  defaultSeniority: SuitabilityLevelId;
  coreSkills: string[];
  toolOptions: string[];
  focusOptions: string[];
  /** What this role actually does — shown on catalog cards. */
  description: string;
};

function role(
  id: string,
  title: string,
  category: string,
  defaultIndustry: string,
  description: string,
  coreSkills: string[],
  toolOptions: string[],
  focusOptions: string[],
  defaultSeniority: SuitabilityLevelId = "mid",
): SuitabilityRoleTemplate {
  return {
    id,
    title,
    category,
    defaultIndustry,
    defaultSeniority,
    coreSkills,
    toolOptions,
    focusOptions,
    description,
  };
}

export const SUITABILITY_ROLE_TEMPLATES: SuitabilityRoleTemplate[] = [
  // ── Software Engineering ──────────────────────────────────────────────
  role("software-engineer", "Software Engineer", "software", "Technology",
    "Builds and maintains software products — writing code, reviewing designs, fixing bugs, and shipping features that users rely on.",
    ["Programming", "Git", "APIs", "Testing", "Debugging"],
    ["TypeScript", "Python", "Java", "Go", "React", "Node.js", "PostgreSQL", "Docker", "AWS"],
    ["System design", "Code quality", "Mentoring", "Reliability"]),
  role("frontend-developer", "Frontend Developer", "software", "Technology",
    "Creates the interfaces people see and use — responsive layouts, accessible components, and smooth client-side experiences.",
    ["HTML/CSS", "JavaScript", "Responsive design", "Accessibility"],
    ["React", "TypeScript", "Next.js", "Vue", "Tailwind CSS", "Storybook", "Vitest"],
    ["Design systems", "Performance", "Accessibility"]),
  role("backend-developer", "Backend Developer", "software", "Technology",
    "Owns the server side of products: APIs, databases, authentication, and the services that keep data and business logic reliable.",
    ["APIs", "Databases", "Auth", "Caching", "Observability"],
    ["Node.js", "Python", "Java", "Go", "PostgreSQL", "Redis", "Kafka", "Docker", "AWS"],
    ["Scalability", "Security", "Data modelling"]),
  role("fullstack-developer", "Full Stack Developer", "software", "Technology",
    "Works across the stack — UI through database — to deliver complete features end to end with minimal handoffs.",
    ["Frontend", "Backend", "Databases", "Deployment"],
    ["React", "TypeScript", "Node.js", "PostgreSQL", "Next.js", "Prisma", "Docker"],
    ["End-to-end ownership", "Product sense"]),
  role("mobile-developer", "Mobile Developer", "software", "Technology",
    "Designs and ships native or cross-platform apps, handling store releases, performance, and platform-specific UX.",
    ["Mobile UI", "App lifecycle", "APIs", "Store releases"],
    ["Swift", "Kotlin", "React Native", "Flutter", "Firebase", "Xcode"],
    ["Offline-first", "App performance"]),
  role("devops-engineer", "DevOps Engineer", "software", "Technology",
    "Automates how software is built, tested, and released — pipelines, infrastructure as code, and production health.",
    ["CI/CD", "Infrastructure as code", "Monitoring", "Linux"],
    ["AWS", "GCP", "Terraform", "Kubernetes", "Docker", "GitHub Actions", "Prometheus"],
    ["Reliability", "Cost optimisation", "Developer experience"]),
  role("platform-engineer", "Platform Engineer", "software", "Technology",
    "Builds internal platforms and tooling so product teams can ship faster — shared services, golden paths, and self-serve infra.",
    ["Internal platforms", "Developer tooling", "Automation", "Standards"],
    ["Kubernetes", "Terraform", "Backstage", "AWS", "Go", "Python"],
    ["Developer experience", "Self-serve platforms"]),
  role("qa-engineer", "QA Engineer", "software", "Technology",
    "Protects product quality through test strategy, automation, exploratory testing, and clear bug reporting.",
    ["Test design", "Bug reporting", "Regression", "Risk assessment"],
    ["Playwright", "Cypress", "Selenium", "Jest", "Postman", "Jira"],
    ["Test automation", "Exploratory testing"]),
  role("embedded-software-engineer", "Embedded Software Engineer", "software", "Technology",
    "Writes software that runs on hardware — firmware, real-time systems, and device drivers with tight resource constraints.",
    ["C/C++", "Real-time systems", "Hardware interfaces", "Debugging"],
    ["C", "C++", "RTOS", "ARM", "JTAG", "Git"],
    ["Low-level performance", "Hardware bring-up"]),
  role("game-developer", "Game Developer", "software", "Entertainment",
    "Builds interactive game experiences — gameplay systems, performance, and content pipelines for players.",
    ["Gameplay programming", "Performance", "Physics", "Version control"],
    ["Unity", "Unreal Engine", "C#", "C++", "Blender"],
    ["Gameplay feel", "Multiplayer"]),

  // ── IT & Cybersecurity ────────────────────────────────────────────────
  role("it-support-specialist", "IT Support Specialist", "it-security", "Technology",
    "Helps employees stay productive by diagnosing device, network, and account issues and keeping workplace tech running.",
    ["Troubleshooting", "Ticketing", "Hardware", "User support"],
    ["ServiceNow", "Jira Service Management", "Microsoft 365", "Active Directory"],
    ["Desktop support", "Onboarding tech"]),
  role("systems-administrator", "Systems Administrator", "it-security", "Technology",
    "Configures and maintains servers, identity, and core IT systems so the organisation’s infrastructure stays stable and secure.",
    ["Servers", "Identity", "Patching", "Networking basics"],
    ["Windows Server", "Linux", "Active Directory", "Azure", "VMware"],
    ["Uptime", "Access management"]),
  role("network-engineer", "Network Engineer", "it-security", "Telecommunications",
    "Designs and operates networks — routing, switching, firewalls, and connectivity that keep people and systems linked.",
    ["Routing", "Switching", "Firewalls", "Troubleshooting"],
    ["Cisco", "Juniper", "Palo Alto", "Wireshark", "Terraform"],
    ["Network reliability", "Security hardening"]),
  role("security-engineer", "Security Engineer", "it-security", "Technology",
    "Reduces cyber risk across apps and infrastructure through threat modelling, controls, monitoring, and incident response.",
    ["Threat modelling", "Vulnerability management", "Secure coding", "Incident response"],
    ["AWS Security", "Okta", "SIEM", "Burp Suite", "Terraform", "Python"],
    ["AppSec", "Cloud security", "Zero trust"]),
  role("cybersecurity-analyst", "Cybersecurity Analyst", "it-security", "Technology",
    "Monitors for threats, investigates alerts, and helps contain incidents before they become breaches.",
    ["SIEM monitoring", "Alert triage", "Investigation", "Reporting"],
    ["Splunk", "Microsoft Sentinel", "CrowdStrike", "Wireshark", "Jira"],
    ["SOC operations", "Threat hunting"]),
  role("cloud-engineer", "Cloud Engineer", "it-security", "Technology",
    "Designs and runs cloud environments — compute, networking, IAM, and cost-aware architectures on major cloud platforms.",
    ["Cloud architecture", "IAM", "Networking", "Automation"],
    ["AWS", "Azure", "GCP", "Terraform", "Kubernetes", "Python"],
    ["Landing zones", "Cost control"]),

  // ── Data & AI ─────────────────────────────────────────────────────────
  role("data-analyst", "Data Analyst", "data-ai", "Technology",
    "Turns raw data into clear insights — querying datasets, building dashboards, and helping teams make better decisions.",
    ["SQL", "Visualisation", "Metrics", "Storytelling"],
    ["SQL", "Excel", "Python", "Tableau", "Looker", "Power BI", "dbt"],
    ["Dashboarding", "Experimentation"]),
  role("data-scientist", "Data Scientist", "data-ai", "Technology",
    "Builds statistical and machine-learning models to answer hard business questions and predict outcomes.",
    ["Statistics", "ML modelling", "Experiment design", "Python"],
    ["Python", "R", "SQL", "scikit-learn", "PyTorch", "Jupyter", "Spark"],
    ["Forecasting", "Causal inference", "NLP"]),
  role("data-engineer", "Data Engineer", "data-ai", "Technology",
    "Builds the pipelines and warehouses that make data trustworthy and available for analytics and ML.",
    ["ETL/ELT", "Data modelling", "Pipelines", "SQL"],
    ["SQL", "Python", "Spark", "Airflow", "dbt", "Snowflake", "BigQuery", "Kafka"],
    ["Warehouse design", "Data quality"]),
  role("analytics-engineer", "Analytics Engineer", "data-ai", "Technology",
    "Creates tested, documented data models so analysts and PMs can self-serve reliable metrics.",
    ["Transformations", "Testing", "Documentation", "SQL"],
    ["dbt", "SQL", "Snowflake", "BigQuery", "Looker", "Git"],
    ["Semantic layer", "Metric governance"]),
  role("bi-analyst", "Business Intelligence Analyst", "data-ai", "Business",
    "Owns reporting that leaders trust — KPIs, executive dashboards, and the narrative behind the numbers.",
    ["KPI design", "Reporting", "SQL", "Stakeholder management"],
    ["Power BI", "Tableau", "Looker", "Excel", "SQL"],
    ["Executive reporting", "Self-serve BI"]),
  role("ml-engineer", "Machine Learning Engineer", "data-ai", "Technology",
    "Takes models from experiment to production — training pipelines, serving, monitoring, and reliability.",
    ["ML pipelines", "Model evaluation", "Feature engineering", "Python"],
    ["Python", "PyTorch", "TensorFlow", "MLflow", "AWS SageMaker", "Docker", "Kubernetes"],
    ["Production ML", "LLM applications"]),
  role("ai-product-specialist", "AI Product Specialist", "data-ai", "Technology",
    "Bridges AI capability and product outcomes — scoping use cases, evaluating models, and guiding responsible adoption.",
    ["AI use cases", "Evaluation", "Prompt design", "Stakeholder alignment"],
    ["OpenAI APIs", "Python", "Notion", "LangChain", "Amplitude"],
    ["GenAI products", "Responsible AI"]),

  // ── Product ───────────────────────────────────────────────────────────
  role("product-manager", "Product Manager", "product", "Technology",
    "Decides what to build and why — prioritising outcomes, aligning stakeholders, and guiding discovery through delivery.",
    ["Roadmapping", "Prioritisation", "User research", "Outcomes"],
    ["Jira", "Linear", "Amplitude", "Mixpanel", "Figma", "Notion", "SQL"],
    ["Discovery", "0-to-1", "Platform products"]),
  role("product-owner", "Product Owner", "product", "Technology",
    "Owns the backlog for a delivery team — clarifying requirements, acceptance criteria, and sprint priorities.",
    ["Backlog management", "Acceptance criteria", "Sprint rituals"],
    ["Jira", "Azure DevOps", "Confluence", "Figma", "Miro"],
    ["Agile delivery", "Release planning"]),
  role("technical-product-manager", "Technical Product Manager", "product", "Technology",
    "Leads product for technical platforms or APIs — balancing developer needs, architecture constraints, and business value.",
    ["Technical roadmaps", "API products", "Stakeholder alignment"],
    ["Jira", "Confluence", "Figma", "Postman", "Amplitude"],
    ["Platform PM", "Developer products"]),
  role("product-operations-manager", "Product Operations Manager", "product", "Technology",
    "Improves how product teams work — tooling, rituals, insights, and processes that scale product organisations.",
    ["Process design", "Tooling", "Insights", "Enablement"],
    ["Jira", "Notion", "Amplitude", "Productboard", "Looker"],
    ["Product ops", "Portfolio cadence"]),

  // ── Design & UX ───────────────────────────────────────────────────────
  role("ux-designer", "UX Designer", "design", "Design",
    "Designs usable experiences grounded in research — flows, wireframes, prototypes, and usability validation.",
    ["User research", "Wireframing", "Prototyping", "Usability testing"],
    ["Figma", "FigJam", "Miro", "UserTesting", "Notion"],
    ["Research synthesis", "Accessibility"]),
  role("ui-designer", "UI Designer", "design", "Design",
    "Crafts visual interface systems — typography, layout, components, and polished handoff to engineering.",
    ["Visual design", "Typography", "Layout", "Component libraries"],
    ["Figma", "Sketch", "Adobe XD", "Storybook"],
    ["Brand systems", "Responsive craft"]),
  role("product-designer", "Product Designer", "design", "Technology",
    "Owns product experience end to end — from problem framing and research through high-fidelity UI.",
    ["End-to-end design", "Prototyping", "Research", "Collaboration"],
    ["Figma", "FigJam", "Maze", "Notion", "Amplitude"],
    ["B2B SaaS", "Growth product", "Mobile product"]),
  role("ux-researcher", "UX Researcher", "design", "Technology",
    "Generates evidence for product decisions through studies, interviews, synthesis, and stakeholder influence.",
    ["Study design", "Interviews", "Synthesis", "Ethics"],
    ["Dovetail", "UserTesting", "Maze", "Figma", "Notion"],
    ["Generative research", "Evaluative research"]),
  role("brand-designer", "Brand Designer", "design", "Marketing",
    "Shapes visual identity — logos, systems, and brand assets that make a company recognisable and consistent.",
    ["Brand systems", "Typography", "Campaign visuals"],
    ["Figma", "Adobe Illustrator", "Photoshop", "After Effects"],
    ["Identity systems", "Campaign design"]),

  // ── Marketing & Growth ────────────────────────────────────────────────
  role("marketing-manager", "Marketing Manager", "marketing", "Marketing",
    "Plans and runs marketing programmes — channel mix, campaigns, budget, and performance against growth goals.",
    ["Campaign planning", "Channel mix", "Budgeting", "Analytics"],
    ["Google Analytics", "HubSpot", "Mailchimp", "Meta Ads", "Google Ads"],
    ["Demand gen", "Brand", "Product marketing"]),
  role("content-marketer", "Content Marketer", "marketing", "Marketing",
    "Creates content that attracts and converts — editorial strategy, writing, SEO, and distribution.",
    ["Editorial strategy", "Writing", "SEO basics", "Distribution"],
    ["WordPress", "Webflow", "GA4", "Ahrefs", "Notion", "Canva"],
    ["Thought leadership", "SEO content"]),
  role("seo-specialist", "SEO Specialist", "marketing", "Marketing",
    "Grows organic visibility through technical SEO, keyword strategy, content briefs, and measurable ranking gains.",
    ["Technical SEO", "Keyword research", "On-page optimisation"],
    ["Ahrefs", "Semrush", "Google Search Console", "Screaming Frog", "GA4"],
    ["Technical audits", "Content SEO"]),
  role("performance-marketer", "Performance Marketer", "marketing", "Marketing",
    "Drives efficient paid acquisition with rigorous testing across ads, creatives, tracking, and ROAS.",
    ["Paid media", "Conversion tracking", "Creative testing", "Budget pacing"],
    ["Google Ads", "Meta Ads", "LinkedIn Ads", "GA4", "Google Tag Manager"],
    ["Acquisition", "Retargeting"]),
  role("growth-marketer", "Growth Marketer", "marketing", "Technology",
    "Finds scalable growth loops — experiments across acquisition, activation, and retention with a data-first mindset.",
    ["Experimentation", "Funnel analysis", "Lifecycle", "Acquisition"],
    ["Amplitude", "Mixpanel", "GA4", "Braze", "SQL", "Notion"],
    ["PLG", "Lifecycle growth"]),
  role("social-media-manager", "Social Media Manager", "marketing", "Media",
    "Builds audience and brand presence across social channels with content calendars, community, and analytics.",
    ["Content calendar", "Community management", "Analytics", "Brand voice"],
    ["Meta Business Suite", "LinkedIn", "TikTok", "Hootsuite", "Canva"],
    ["Organic growth", "Influencer collabs"]),
  role("product-marketing-manager", "Product Marketing Manager", "marketing", "Technology",
    "Owns positioning, messaging, launches, and sales enablement so the market understands why the product wins.",
    ["Positioning", "Messaging", "Launch planning", "Competitive intel"],
    ["Notion", "Figma", "Gong", "HubSpot", "Amplitude"],
    ["Launches", "Competitive battles"]),
  role("email-marketing-specialist", "Email Marketing Specialist", "marketing", "Marketing",
    "Designs lifecycle and campaign email programmes that nurture leads and customers with measurable engagement.",
    ["Lifecycle email", "Segmentation", "Copy", "A/B testing"],
    ["Braze", "Customer.io", "Mailchimp", "Klaviyo", "HubSpot", "GA4"],
    ["Retention", "Nurture sequences"]),

  // ── Sales ─────────────────────────────────────────────────────────────
  role("sales-representative", "Sales Representative", "sales", "Sales",
    "Generates pipeline and closes deals through prospecting, discovery, demos, and disciplined CRM hygiene.",
    ["Prospecting", "Discovery", "Objection handling", "Closing"],
    ["Salesforce", "HubSpot", "Outreach", "LinkedIn Sales Navigator", "Gong"],
    ["Outbound", "Inbound"]),
  role("account-executive", "Account Executive", "sales", "Sales",
    "Owns the full sales cycle from qualified opportunity to close — multi-threading, negotiating, and forecasting.",
    ["Discovery", "Demo", "Negotiation", "Forecasting"],
    ["Salesforce", "HubSpot", "Gong", "LinkedIn Sales Navigator", "Outreach"],
    ["Mid-market", "Enterprise", "New logo"]),
  role("sdr", "Sales Development Representative", "sales", "Sales",
    "Creates qualified pipeline for AEs through outbound prospecting, inbound qualification, and booked meetings.",
    ["Outbound prospecting", "Qualification", "Messaging", "CRM"],
    ["Salesforce", "HubSpot", "Outreach", "Salesloft", "Apollo", "LinkedIn Sales Navigator"],
    ["Cold outbound", "Inbound qualification"]),
  role("account-manager", "Account Manager", "sales", "Sales",
    "Grows and protects existing customer relationships — renewals, expansion, and ongoing commercial partnership.",
    ["Relationship management", "Upsell", "Renewals", "Forecasting"],
    ["Salesforce", "HubSpot", "Gainsight", "Notion", "Excel"],
    ["Strategic accounts", "Cross-sell"]),
  role("sales-engineer", "Sales Engineer", "sales", "Technology",
    "Supports complex technical sales — demos, proof of concepts, and translating product capability into customer value.",
    ["Technical demos", "POCs", "Solution design", "Objection handling"],
    ["Salesforce", "Demo environments", "Notion", "Diagramming tools"],
    ["Enterprise SE", "Solutions consulting"]),
  role("sales-operations-analyst", "Sales Operations Analyst", "sales", "Sales",
    "Makes the sales machine measurable — CRM processes, forecasting support, territory insights, and enablement data.",
    ["CRM admin", "Reporting", "Process design", "Forecast support"],
    ["Salesforce", "Excel", "Tableau", "Gong", "Outreach"],
    ["RevOps", "Pipeline hygiene"]),

  // ── Customer Success & Support ────────────────────────────────────────
  role("customer-success-manager", "Customer Success Manager", "customer", "Customer Success",
    "Helps customers achieve outcomes, renew, and expand — onboarding, health scoring, and executive relationships.",
    ["Onboarding", "Retention", "Expansion", "Health scoring"],
    ["Gainsight", "Salesforce", "HubSpot", "Intercom", "Gong"],
    ["Renewals", "Adoption"]),
  role("customer-support-specialist", "Customer Support Specialist", "customer", "Customer Success",
    "Resolves customer issues quickly and clearly through tickets, chat, and empathetic product guidance.",
    ["Ticket triage", "Empathy", "Product knowledge", "Documentation"],
    ["Zendesk", "Intercom", "Freshdesk", "Salesforce Service Cloud", "Notion"],
    ["Live chat", "Email support"]),
  role("technical-support-engineer", "Technical Support Engineer", "customer", "Technology",
    "Solves complex product issues for technical customers — logs, reproduction, and clear escalation paths.",
    ["Troubleshooting", "Logs", "Reproduction", "Knowledge base"],
    ["Jira", "Zendesk", "Datadog", "SQL", "Postman"],
    ["L2/L3 support", "Enterprise customers"]),
  role("implementation-specialist", "Implementation Specialist", "customer", "Technology",
    "Gets customers live successfully — configuring products, migrating data, training users, and managing go-lives.",
    ["Configuration", "Project coordination", "Training", "Data migration"],
    ["Salesforce", "Jira", "Notion", "Customer success platforms"],
    ["Onboarding", "Enterprise implementations"]),

  // ── Finance & Accounting ──────────────────────────────────────────────
  role("financial-analyst", "Financial Analyst", "finance", "Finance",
    "Models performance and advises leaders — forecasts, variance analysis, and clear recommendations from the numbers.",
    ["Financial modelling", "Forecasting", "Variance analysis", "Excel"],
    ["Excel", "Power BI", "SQL", "Anaplan", "Adaptive Insights"],
    ["FP&A", "Investment analysis"]),
  role("accountant", "Accountant", "finance", "Finance",
    "Keeps financial records accurate and timely — reconciliations, reporting, controls, and month-end close support.",
    ["Bookkeeping", "Reconciliations", "Reporting", "Controls"],
    ["Xero", "QuickBooks", "Sage", "Excel", "NetSuite"],
    ["Management accounts", "Month-end close"]),
  role("controller", "Controller", "finance", "Finance",
    "Owns accounting operations and the integrity of the books — close, controls, audit readiness, and team leadership.",
    ["Financial close", "Controls", "Reporting", "Team leadership"],
    ["NetSuite", "SAP", "Excel", "BlackLine", "Workday Financials"],
    ["Multi-entity", "Process improvement"]),
  role("fp-and-a-manager", "FP&A Manager", "finance", "Finance",
    "Leads planning cycles — budgeting, scenarios, board-ready narratives, and partnering with the business.",
    ["Budgeting", "Forecasting", "Scenario planning", "Executive reporting"],
    ["Excel", "Anaplan", "Adaptive Insights", "Power BI", "SQL"],
    ["Headcount planning", "Unit economics"]),
  role("accounts-payable-specialist", "Accounts Payable Specialist", "finance", "Finance",
    "Processes supplier invoices accurately and on time — matching, approvals, payments, and vendor queries.",
    ["Invoice processing", "Vendor management", "Accuracy", "Deadlines"],
    ["NetSuite", "Xero", "SAP", "Excel", "Concur"],
    ["Payment runs", "Vendor relations"]),
  role("treasury-analyst", "Treasury Analyst", "finance", "Banking",
    "Manages cash, liquidity, and banking relationships — forecasting cash needs and supporting funding decisions.",
    ["Cash forecasting", "Banking", "Liquidity", "Risk awareness"],
    ["Excel", "Treasury systems", "Bloomberg", "SAP"],
    ["Cash management", "FX exposure"]),

  // ── People & HR ───────────────────────────────────────────────────────
  role("hr-generalist", "HR Generalist", "hr", "Human Resources",
    "Supports the employee lifecycle — policy, employee relations, onboarding, and day-to-day people operations.",
    ["Employee relations", "Policy", "Onboarding", "Performance cycles"],
    ["Workday", "BambooHR", "Greenhouse", "Notion", "Excel"],
    ["ER cases", "HR ops"]),
  role("recruiter", "Recruiter", "hr", "Human Resources",
    "Finds and closes great candidates — sourcing, screening, coordinating interviews, and managing offers.",
    ["Sourcing", "Screening", "Interview coordination", "Candidate experience"],
    ["Greenhouse", "Lever", "Workday", "LinkedIn Recruiter", "Ashby"],
    ["Technical recruiting", "Volume hiring"]),
  role("people-operations-manager", "People Operations Manager", "hr", "Human Resources",
    "Runs the systems and processes that scale people teams — HRIS, workflows, compliance, and reporting.",
    ["HR systems", "Process design", "Compliance", "Reporting"],
    ["Workday", "BambooHR", "Rippling", "Notion", "Excel"],
    ["HRIS", "Comp cycles"]),
  role("learning-development-specialist", "Learning & Development Specialist", "hr", "Human Resources",
    "Designs learning that improves performance — needs analysis, curricula, facilitation, and measurement.",
    ["Needs analysis", "Curriculum design", "Facilitation", "Measurement"],
    ["Cornerstone", "Docebo", "Notion", "Figma", "Zoom"],
    ["Leadership programmes", "Skills academies"]),
  role("compensation-analyst", "Compensation Analyst", "hr", "Human Resources",
    "Builds fair pay structures — benchmarking, banding, cycle modelling, and advice to managers on offers.",
    ["Benchmarking", "Pay bands", "Modelling", "Confidentiality"],
    ["Excel", "Workday", "Radford", "Levels.fyi data tools"],
    ["Comp cycles", "Equity programmes"]),

  // ── Operations & Supply Chain ─────────────────────────────────────────
  role("operations-manager", "Operations Manager", "operations", "Operations",
    "Makes the organisation run more efficiently — processes, vendors, metrics, and cross-functional coordination.",
    ["Process design", "Metrics", "Vendor management", "Continuous improvement"],
    ["Excel", "Notion", "Asana", "Jira", "Salesforce", "Looker"],
    ["BizOps", "Revenue ops"]),
  role("supply-chain-analyst", "Supply Chain Analyst", "operations", "Manufacturing",
    "Analyses demand, inventory, and supplier performance to keep goods flowing at the right cost and service level.",
    ["Demand planning", "Inventory analysis", "Supplier performance"],
    ["Excel", "SAP", "Oracle", "Power BI", "SQL"],
    ["Inventory optimisation", "S&OP"]),
  role("logistics-coordinator", "Logistics Coordinator", "operations", "Logistics",
    "Coordinates shipments, carriers, and delivery schedules so goods arrive on time with clear tracking and escalation.",
    ["Shipment coordination", "Carrier management", "Scheduling", "Documentation"],
    ["TMS systems", "Excel", "SAP", "Email / EDI tools"],
    ["Inbound logistics", "Last-mile"]),
  role("procurement-specialist", "Procurement Specialist", "operations", "Operations",
    "Sources goods and services well — RFPs, vendor negotiation, contracts, and cost control without blocking the business.",
    ["Sourcing", "Negotiation", "Vendor management", "Contracts"],
    ["SAP Ariba", "Coupa", "Excel", "DocuSign"],
    ["Strategic sourcing", "Cost savings"]),
  role("facilities-manager", "Facilities Manager", "operations", "Operations",
    "Keeps workplaces safe, functional, and cost-effective — vendors, maintenance, space, and day-to-day site operations.",
    ["Vendor management", "Maintenance", "Health & safety", "Budgeting"],
    ["CAFM systems", "Excel", "Microsoft 365"],
    ["Office ops", "Multi-site"]),

  // ── Project & Program Management ──────────────────────────────────────
  role("project-manager", "Project Manager", "project", "Business",
    "Delivers projects on time and budget — planning, risk, stakeholder updates, and keeping scope under control.",
    ["Planning", "Risk management", "Stakeholder updates", "Scope control"],
    ["Jira", "Asana", "Monday.com", "MS Project", "Confluence", "Smartsheet"],
    ["Agile delivery", "Cross-functional launches"]),
  role("program-manager", "Program Manager", "project", "Technology",
    "Orchestrates related projects toward a strategic outcome — multi-workstream coordination and executive communication.",
    ["Multi-workstream coordination", "Roadmap alignment", "Risk", "Exec communication"],
    ["Jira", "Asana", "Notion", "Confluence", "Smartsheet"],
    ["Transformation", "Platform programmes"]),
  role("scrum-master", "Scrum Master", "project", "Technology",
    "Enables teams to deliver iteratively — facilitating rituals, removing impediments, and coaching healthy agile practice.",
    ["Facilitation", "Impediment removal", "Agile coaching", "Team health"],
    ["Jira", "Azure DevOps", "Miro", "Confluence", "Slack"],
    ["Team coaching", "Delivery predictability"]),
  role("delivery-manager", "Delivery Manager", "project", "Technology",
    "Owns predictable delivery for one or more teams — capacity, quality, stakeholder trust, and continuous improvement.",
    ["Delivery planning", "Capacity", "Quality", "Stakeholder trust"],
    ["Jira", "Linear", "Notion", "Confluence", "Looker"],
    ["Engineering delivery", "Client delivery"]),

  // ── Healthcare & Clinical ─────────────────────────────────────────────
  role("registered-nurse", "Registered Nurse", "healthcare", "Healthcare",
    "Delivers safe, evidence-based patient care — assessment, treatment support, documentation, and team communication.",
    ["Patient care", "Clinical assessment", "Documentation", "Medication safety"],
    ["Epic", "Cerner", "Meditech", "Pyxis"],
    ["Acute care", "Community care"]),
  role("healthcare-administrator", "Healthcare Administrator", "healthcare", "Healthcare",
    "Keeps healthcare services organised and compliant — operations, scheduling, quality metrics, and patient access.",
    ["Operations", "Compliance", "Scheduling", "Quality metrics"],
    ["Epic", "Cerner", "Excel", "Salesforce Health Cloud"],
    ["Clinic ops", "Patient access"]),
  role("clinical-research-associate", "Clinical Research Associate", "healthcare", "Pharmaceuticals",
    "Monitors clinical trial sites for protocol compliance, data quality, and Good Clinical Practice standards.",
    ["Protocol compliance", "Site monitoring", "Documentation", "GCP"],
    ["EDC systems", "CTMS", "Veeva", "Excel"],
    ["On-site monitoring", "Remote monitoring"]),
  role("medical-receptionist", "Medical Receptionist", "healthcare", "Healthcare",
    "Is the first reliable point of contact for patients — intake, scheduling, confidentiality, and front-desk service.",
    ["Patient intake", "Scheduling", "Confidentiality", "Customer service"],
    ["Epic", "Cerner", "Phreesia", "Microsoft Outlook"],
    ["Front desk", "Specialty practices"]),
  role("pharmacy-technician", "Pharmacy Technician", "healthcare", "Healthcare",
    "Supports pharmacists in preparing and dispensing medications accurately while maintaining inventory and records.",
    ["Dispensing support", "Accuracy", "Inventory", "Patient interaction"],
    ["Pharmacy management systems", "Pyxis", "Excel"],
    ["Retail pharmacy", "Hospital pharmacy"]),
  role("physiotherapist", "Physiotherapist", "healthcare", "Healthcare",
    "Helps patients recover movement and function through assessment, treatment plans, and guided rehabilitation.",
    ["Assessment", "Treatment planning", "Rehabilitation", "Patient education"],
    ["Clinical notes systems", "Exercise prescription tools"],
    ["MSK", "Sports rehab"]),

  // ── Legal & Compliance ────────────────────────────────────────────────
  role("paralegal", "Paralegal", "legal", "Legal",
    "Supports lawyers with research, drafting, case organisation, and deadline tracking under confidentiality rules.",
    ["Legal research", "Document drafting", "Case management", "Deadlines"],
    ["Westlaw", "LexisNexis", "Clio", "Relativity", "Word", "Excel"],
    ["Litigation support", "Corporate", "Contracts"]),
  role("compliance-officer", "Compliance Officer", "legal", "Legal",
    "Builds and enforces programmes that keep the organisation compliant — policy, risk, investigations, and training.",
    ["Policy", "Risk assessment", "Investigations", "Training"],
    ["ServiceNow", "Excel", "Workday", "GRC platforms"],
    ["Financial services", "Data privacy"]),
  role("contracts-manager", "Contracts Manager", "legal", "Legal",
    "Owns contract quality and speed — review, negotiation support, clause libraries, and lifecycle management.",
    ["Contract review", "Negotiation support", "Risk flags", "Lifecycle management"],
    ["Ironclad", "DocuSign", "Conga", "Salesforce", "Word"],
    ["Vendor contracts", "Customer contracts"]),
  role("privacy-analyst", "Privacy Analyst", "legal", "Technology",
    "Helps the organisation handle personal data lawfully — assessments, DSRs, vendor reviews, and privacy-by-design advice.",
    ["DPIAs", "Data subject requests", "Policy", "Vendor review"],
    ["OneTrust", "TrustArc", "Jira", "Notion", "Excel"],
    ["GDPR", "Product privacy"]),

  // ── Education & Training ──────────────────────────────────────────────
  role("teacher", "Teacher", "education", "Education",
    "Plans and delivers learning that helps every student progress — lessons, assessment, and classroom leadership.",
    ["Lesson planning", "Classroom management", "Assessment", "Differentiation"],
    ["Google Classroom", "Microsoft Teams", "PowerPoint", "Kahoot", "SIS platforms"],
    ["Primary", "Secondary"]),
  role("instructional-designer", "Instructional Designer", "education", "Education",
    "Designs learning experiences that change knowledge and behaviour — objectives, content, assessments, and iteration.",
    ["Learning objectives", "Curriculum design", "Assessments", "Multimedia"],
    ["Articulate 360", "Captivate", "Figma", "LMS admin", "Canva"],
    ["Corporate L&D", "eLearning"]),
  role("academic-advisor", "Academic Advisor", "education", "Education",
    "Guides students through academic choices and progress — degree planning, interventions, and supportive advising.",
    ["Student advising", "Degree planning", "Documentation", "Empathy"],
    ["SIS platforms", "CRM for education", "Microsoft 365", "Zoom"],
    ["Undergraduate advising", "At-risk interventions"]),
  role("corporate-trainer", "Corporate Trainer", "education", "Business",
    "Delivers workplace training that sticks — workshops, enablement programmes, and coaching for skills on the job.",
    ["Facilitation", "Curriculum delivery", "Coaching", "Measurement"],
    ["Zoom", "LMS platforms", "PowerPoint", "Notion"],
    ["Sales enablement", "Onboarding training"]),

  // ── Business & Strategy ───────────────────────────────────────────────
  role("business-analyst", "Business Analyst", "strategy", "Business",
    "Translates business needs into clear, buildable requirements — process maps, stakeholder interviews, and acceptance criteria.",
    ["Requirements", "Process mapping", "Stakeholder interviews", "Documentation"],
    ["Jira", "Confluence", "Visio", "Miro", "Excel", "SQL"],
    ["Digital transformation", "Process improvement"]),
  role("management-consultant", "Management Consultant", "strategy", "Consulting",
    "Helps clients solve ambiguous problems with structured analysis, recommendations, and slide-ready storytelling.",
    ["Problem structuring", "Analysis", "Slide storytelling", "Client management"],
    ["Excel", "PowerPoint", "SQL", "Tableau"],
    ["Strategy", "Operations", "Digital"]),
  role("strategy-manager", "Strategy Manager", "strategy", "Business",
    "Shapes and tracks strategic bets — market analysis, opportunity sizing, initiative planning, and executive updates.",
    ["Market analysis", "Opportunity sizing", "Initiative planning"],
    ["Excel", "PowerPoint", "Notion", "SQL", "Tableau"],
    ["Corporate strategy", "Growth strategy"]),
  role("chief-of-staff", "Chief of Staff", "strategy", "Business",
    "Multiplies an executive’s leverage — priorities, decision prep, cross-functional drive, and confidential coordination.",
    ["Priority setting", "Executive communication", "Cross-functional drive"],
    ["Notion", "Asana", "Slack", "Google Workspace", "Excel"],
    ["Founder support", "OKR cadence"]),
  role("business-operations-analyst", "Business Operations Analyst", "strategy", "Business",
    "Improves how the business runs — analyses workflows, builds models, and drives operational initiatives with data.",
    ["Process analysis", "Modelling", "Stakeholder management", "Reporting"],
    ["Excel", "SQL", "Looker", "Notion", "Salesforce"],
    ["BizOps", "Revenue operations"]),

  // ── Media & Communications ────────────────────────────────────────────
  role("communications-manager", "Communications Manager", "media", "Media",
    "Shapes internal and external narratives — messaging, announcements, media relations, and executive communications.",
    ["Messaging", "Writing", "Stakeholder alignment", "Media relations"],
    ["Notion", "Google Docs", "Canva", "Media monitoring tools"],
    ["Internal comms", "External comms"]),
  role("public-relations-specialist", "Public Relations Specialist", "media", "Media",
    "Builds reputation through media coverage, relationships with journalists, and clear crisis-ready messaging.",
    ["Media outreach", "Press writing", "Relationship building"],
    ["Cision", "Muck Rack", "Google Alerts", "Canva"],
    ["Media relations", "Crisis PR"]),
  role("technical-writer", "Technical Writer", "media", "Technology",
    "Makes complex products understandable — docs, guides, API references, and content that helps users succeed.",
    ["Clear writing", "Information architecture", "Audience awareness"],
    ["MadCap Flare", "GitBook", "Notion", "Markdown", "Figma"],
    ["Developer docs", "Help centres"]),
  role("copywriter", "Copywriter", "media", "Advertising",
    "Writes persuasive copy for campaigns, websites, and products that convert attention into action.",
    ["Persuasive writing", "Brand voice", "Brief interpretation"],
    ["Google Docs", "Notion", "Figma", "Grammarly"],
    ["Performance copy", "Brand campaigns"]),

  // ── Hospitality & Retail ──────────────────────────────────────────────
  role("store-manager", "Store Manager", "hospitality", "Retail",
    "Runs a retail location end to end — team leadership, sales targets, inventory, customer experience, and standards.",
    ["Team leadership", "Sales targets", "Inventory", "Customer experience"],
    ["POS systems", "Workforce scheduling", "Excel"],
    ["High-street retail", "Flagship stores"]),
  role("hotel-operations-manager", "Hotel Operations Manager", "hospitality", "Hospitality",
    "Delivers a smooth guest experience — front-of-house, housekeeping coordination, service standards, and occupancy goals.",
    ["Guest experience", "Team coordination", "Service standards", "Scheduling"],
    ["PMS systems", "Excel", "Workforce tools"],
    ["Front office", "Housekeeping ops"]),
  role("restaurant-manager", "Restaurant Manager", "hospitality", "Hospitality",
    "Leads restaurant service and operations — staff, quality, cost control, and a consistent guest experience.",
    ["Service leadership", "Cost control", "Scheduling", "Quality"],
    ["POS systems", "Reservations platforms", "Excel"],
    ["F&B operations", "Team leadership"]),
  role("retail-buyer", "Retail Buyer", "hospitality", "Retail",
    "Selects and plans merchandise that sells — assortment, supplier negotiation, margins, and seasonal planning.",
    ["Assortment planning", "Supplier negotiation", "Margins", "Forecasting"],
    ["Excel", "Retail planning systems", "ERP tools"],
    ["Category management", "Seasonal buys"]),

  // ── Skilled Trades & Field ────────────────────────────────────────────
  role("electrician", "Electrician", "skilled", "Construction",
    "Installs and maintains electrical systems safely — wiring, testing, diagnostics, and compliance with codes.",
    ["Electrical installation", "Diagnostics", "Safety", "Codes"],
    ["Multimeters", "Job management apps", "CAD viewers"],
    ["Residential", "Commercial"]),
  role("hvac-technician", "HVAC Technician", "skilled", "Construction",
    "Installs and repairs heating, ventilation, and cooling systems — diagnostics, maintenance, and customer communication.",
    ["Diagnostics", "Installation", "Maintenance", "Safety"],
    ["Job management apps", "Manufacturer diagnostic tools"],
    ["Residential HVAC", "Commercial HVAC"]),
  role("field-service-technician", "Field Service Technician", "skilled", "Manufacturing",
    "Repairs and maintains equipment on customer sites — diagnosing faults, fixing issues, and documenting work clearly.",
    ["Diagnostics", "Repair", "Customer communication", "Documentation"],
    ["Salesforce Field Service", "ServiceMax", "Mobile job apps"],
    ["On-site repair", "Preventive maintenance"]),
  role("warehouse-supervisor", "Warehouse Supervisor", "skilled", "Logistics",
    "Leads warehouse teams safely and efficiently — inbound/outbound flow, inventory accuracy, and shift performance.",
    ["Team leadership", "Inventory accuracy", "Safety", "Shift planning"],
    ["WMS systems", "Scanners", "Excel"],
    ["Fulfilment", "Distribution"]),

  // ── Public & Nonprofit ────────────────────────────────────────────────
  role("policy-advisor", "Policy Advisor", "public", "Government",
    "Researches and advises on policy options — briefing decision-makers with clear analysis and stakeholder context.",
    ["Policy analysis", "Briefing", "Research", "Stakeholder mapping"],
    ["Word", "Excel", "Notion", "Research databases"],
    ["Public policy", "Regulatory advice"]),
  role("grant-writer", "Grant Writer", "public", "Nonprofit",
    "Wins funding for missions that matter — compelling proposals, budgets, and reporting that meet funder requirements.",
    ["Proposal writing", "Budget narratives", "Funder research"],
    ["Word", "Excel", "Grant management systems"],
    ["Foundation grants", "Government grants"]),
  role("community-manager-nonprofit", "Community Programme Manager", "public", "Nonprofit",
    "Designs and runs community programmes — partnerships, delivery, measurement, and impact storytelling.",
    ["Programme design", "Partnerships", "Delivery", "Impact measurement"],
    ["CRM tools", "Notion", "Excel", "Survey tools"],
    ["Community outreach", "Impact reporting"]),
  role("case-worker", "Case Worker", "public", "Nonprofit",
    "Supports individuals through complex needs — assessment, care planning, advocacy, and careful documentation.",
    ["Assessment", "Care planning", "Advocacy", "Documentation"],
    ["Case management systems", "Microsoft 365"],
    ["Social care", "Housing support"]),
];

export function getSuitabilityRoleById(id: string): SuitabilityRoleTemplate | undefined {
  return SUITABILITY_ROLE_TEMPLATES.find((r) => r.id === id);
}

export function listSuitabilityCategories(): Array<{ id: string; label: string; count: number }> {
  return SUITABILITY_CATEGORIES.map((c) => ({
    ...c,
    count: SUITABILITY_ROLE_TEMPLATES.filter((r) => r.category === c.id).length,
  })).filter((c) => c.count > 0);
}
