import type { Destination, PathStep } from "./types"

function step(
  id: string,
  title: string,
  whatToDo: string,
  extras: Partial<Omit<PathStep, "id" | "title" | "whatToDo">> = {},
): PathStep {
  return {
    id,
    title,
    whatToDo,
    documents: extras.documents ?? [],
    costGbp: extras.costGbp ?? 0,
    time: extras.time ?? "Varies",
    whoCanHelp: extras.whoCanHelp ?? "You",
  }
}

export const DESTINATIONS: Destination[] = [
  {
    slug: "canada",
    name: "Canada",
    flag: "🇨🇦",
    climate: "cold",
    summary: "Skilled immigration is a realistic route for experienced professionals who can prove English and funds.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: true,
    settlementBase: 80,
    prepMonths: 9,
    documentCount: 12,
    housingGbp: 1400,
    costs: { visa: 1450, flight: 720, deposit: 2400, rent: 1550, emergency: 3200, documents: 680, other: 3300 },
    jobStrength: { tech: "Strong", health: "Strong", education: "Moderate", other: "Moderate" },
    jobCount: { tech: 36, health: 44, education: 18, other: 14 },
    routes: [
      {
        id: "express-entry",
        name: "Skilled immigration",
        featured: true,
        skilledBands: ["tech", "health", "education"],
        minEducation: "bachelor",
        minExperience: 1,
        maxAge: 45,
        minEnglish: "intermediate",
        fitReason: "Your occupation sits in skilled categories, and English plus a degree are the usual starting point.",
        steps: [
          step("language", "English or French test", "Book an accepted language test and keep the result with your profile.", {
            documents: ["Passport", "Test booking"],
            costGbp: 280,
            time: "2–4 weeks",
            whoCanHelp: "An approved test centre",
          }),
          step("eca", "Education assessment", "Have your highest qualification assessed against Canadian standards.", {
            documents: ["Degree certificate", "Transcripts"],
            costGbp: 220,
            time: "4–12 weeks",
            whoCanHelp: "A designated assessment body",
          }),
          step("profile", "Express Entry profile", "Create the profile once language and education results are in.", {
            documents: ["Language result", "Education assessment", "Work references"],
            costGbp: 0,
            time: "1 week",
            whoCanHelp: "You, or a regulated adviser",
          }),
          step("invite", "Invitation to apply", "Wait for a round of invitations. A stronger score shortens this wait.", {
            documents: ["Updated profile"],
            costGbp: 0,
            time: "Often several months",
            whoCanHelp: "You",
          }),
          step("checks", "Medical and police checks", "Complete the medical and police certificates after you are invited.", {
            documents: ["Police certificate", "Medical report"],
            costGbp: 340,
            time: "3–8 weeks",
            whoCanHelp: "A panel physician and the police authority",
          }),
          step("decision", "Visa decision", "Submit the full application and respond quickly if more evidence is requested.", {
            documents: ["Proof of funds", "Passport"],
            costGbp: 1100,
            time: "Several months",
            whoCanHelp: "A regulated immigration adviser",
          }),
        ],
      },
      {
        id: "study",
        name: "Student",
        alwaysPotential: true,
        fitReason: "A study permit is a separate path and needs an acceptance letter plus funds for tuition.",
        steps: [
          step("offer", "School acceptance", "Apply to a designated learning institution.", { time: "1–4 months", whoCanHelp: "The school" }),
          step("permit", "Study permit", "Apply with the acceptance letter and proof you can pay.", { time: "Several weeks", whoCanHelp: "You" }),
        ],
      },
      {
        id: "family",
        name: "Family",
        familyOnly: true,
        fitReason: "A partner or relative in Canada can open a family route.",
        steps: [
          step("sponsor", "Confirm a sponsor", "Check that the person in Canada can sponsor you.", { time: "1–2 weeks", whoCanHelp: "Your family member" }),
        ],
      },
    ],
    settlement: [
      { id: "sin", title: "Apply for a Social Insurance Number", detail: "You need it before most employers can pay you." },
      { id: "bank", title: "Open a bank account", detail: "Take your passport and immigration document to a bank." },
      { id: "health", title: "Register for provincial health cover", detail: "Coverage often has a waiting period. Keep travel insurance until it starts." },
      { id: "sim", title: "Get a SIM", detail: "A local number unlocks banking and government accounts." },
      { id: "housing", title: "Find longer-term housing", detail: "Start from temporary accommodation, then sign a lease." },
      { id: "tax", title: "Understand your tax residency", detail: "Newcomers usually file a first return the following spring." },
      { id: "school", title: "Register children for school", detail: "Public schools enrol by address. Bring passports and proof of address." },
      { id: "licence", title: "Exchange or apply for a driving licence", detail: "Rules depend on the province and how long you have been driving." },
    ],
    channels: ["Moving to Canada", "Express Entry", "Jobs", "Housing", "Toronto", "Vancouver", "Students", "Families", "New arrivals"],
  },
  {
    slug: "germany",
    name: "Germany",
    flag: "🇩🇪",
    climate: "mild",
    summary: "The Opportunity Card is built for skilled people who do not yet have a job offer.",
    englishFriendly: false,
    englishAccepted: true,
    englishTestExpected: false,
    recommendLanguage: "German",
    settlementBase: 74,
    prepMonths: 7,
    documentCount: 10,
    housingGbp: 1100,
    costs: { visa: 500, flight: 650, deposit: 2000, rent: 1100, emergency: 3000, documents: 400, other: 1850 },
    jobStrength: { tech: "Strong", health: "Strong", education: "Limited", other: "Moderate" },
    jobCount: { tech: 31, health: 27, education: 8, other: 12 },
    routes: [
      {
        id: "opportunity-card",
        name: "Opportunity Card",
        featured: true,
        skilledBands: ["tech", "health", "education"],
        minEducation: "bachelor",
        minEnglish: "intermediate",
        recommendLanguage: "German",
        fitReason: "A recognised qualification and work experience can earn enough points, with language making the file stronger.",
        steps: [
          step("points", "Check your points", "Add up qualification, experience, age, and language before you apply.", {
            documents: ["CV", "Degree"],
            costGbp: 0,
            time: "1 week",
            whoCanHelp: "You",
          }),
          step("language", "Language evidence", "Book German or use a strong English result. German improves both points and daily life.", {
            documents: ["Language certificate"],
            costGbp: 220,
            time: "4–12 weeks",
            whoCanHelp: "A language school",
          }),
          step("funds", "Show funds", "Prepare the blocked-account or savings evidence the route asks for.", {
            documents: ["Bank statements"],
            costGbp: 0,
            time: "1–2 weeks",
            whoCanHelp: "Your bank",
          }),
          step("apply", "Submit the application", "Apply at the mission that covers where you live.", {
            documents: ["Passport", "Qualification", "Insurance"],
            costGbp: 500,
            time: "Several weeks",
            whoCanHelp: "The visa mission, or a regulated adviser",
          }),
          step("insurance", "Health insurance", "Line up cover that satisfies the visa before you travel.", {
            documents: ["Insurance certificate"],
            costGbp: 180,
            time: "1 week",
            whoCanHelp: "An insurer that covers newcomers",
          }),
          step("decision", "Visa decision", "Track the file and book travel only after the visa is issued.", {
            documents: ["Passport"],
            costGbp: 0,
            time: "Several weeks to a few months",
            whoCanHelp: "You",
          }),
        ],
      },
      {
        id: "blue-card",
        name: "EU Blue Card",
        needsSponsor: true,
        minEducation: "bachelor",
        fitReason: "This route needs a job offer at the salary level set for your occupation.",
        steps: [
          step("offer", "Get a qualifying offer", "The contract has to meet the salary threshold for the role.", { time: "Varies", whoCanHelp: "The employer" }),
        ],
      },
      {
        id: "study",
        name: "Student",
        alwaysPotential: true,
        fitReason: "University admission is a separate route and needs tuition and living funds.",
        steps: [step("admit", "University admission", "Apply for a programme and a student visa.", { time: "1–4 months", whoCanHelp: "The university" })],
      },
    ],
    settlement: [
      { id: "address", title: "Register your address", detail: "Book Anmeldung at the local citizens' office within the first two weeks." },
      { id: "tax", title: "Get a tax ID", detail: "It is posted to your registered address after you register." },
      { id: "bank", title: "Open a bank account", detail: "Most banks ask for your registration certificate and passport." },
      { id: "health", title: "Get health insurance", detail: "Public or private cover is mandatory. Start this before your first day of work." },
      { id: "sim", title: "Get a SIM", detail: "A German number is needed for banking and appointments." },
      { id: "housing", title: "Find permanent accommodation", detail: "Landlords usually ask for SCHUFA, payslips, and a registration certificate." },
      { id: "school", title: "Register a child for school", detail: "The local school office places children by address." },
      { id: "licence", title: "Exchange your driving licence", detail: "Some licences must be exchanged within six months." },
      { id: "transport", title: "Understand local transport", detail: "A monthly transit pass is often cheaper than single tickets." },
      { id: "utilities", title: "Set up utilities", detail: "If they are not in the rent, contract electricity in your name." },
    ],
    channels: ["Moving to Germany", "Opportunity Card", "Jobs", "Housing", "Berlin", "Munich", "Students", "Families", "New arrivals"],
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    flag: "🇬🇧",
    climate: "mild",
    summary: "Most skilled workers need a licensed sponsor. Talent and study routes exist alongside that.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: false,
    settlementBase: 78,
    prepMonths: 10,
    documentCount: 9,
    housingGbp: 1600,
    costs: { visa: 4200, flight: 420, deposit: 2400, rent: 1800, emergency: 3000, documents: 480, other: 1700 },
    jobStrength: { tech: "Strong", health: "Strong", education: "Moderate", other: "Limited" },
    jobCount: { tech: 43, health: 51, education: 16, other: 11 },
    routes: [
      {
        id: "skilled-worker",
        name: "Skilled Worker",
        featured: true,
        needsSponsor: true,
        minEnglish: "intermediate",
        fitReason: "A licensed employer has to assign a Certificate of Sponsorship before you can apply.",
        steps: [
          step("sponsor", "Find a licensed sponsor", "Search roles that say they can sponsor a Skilled Worker visa.", {
            documents: ["CV", "Right-to-work explanation"],
            costGbp: 0,
            time: "Often the longest step",
            whoCanHelp: "Employers on the sponsor register",
          }),
          step("cos", "Certificate of Sponsorship", "The employer assigns this. You cannot apply without the reference number.", {
            documents: ["Job offer", "Sponsorship reference"],
            costGbp: 0,
            time: "1–4 weeks after the offer",
            whoCanHelp: "The employer's HR team",
          }),
          step("english", "English evidence", "Use an accepted test or a degree taught in English.", {
            documents: ["English evidence"],
            costGbp: 200,
            time: "2–4 weeks",
            whoCanHelp: "An approved test centre",
          }),
          step("apply", "Visa application", "Apply online, pay the fee and the health surcharge, then book biometrics.", {
            documents: ["Passport", "Sponsorship reference", "Bank statements"],
            costGbp: 4200,
            time: "3–8 weeks",
            whoCanHelp: "You, or an immigration adviser",
          }),
          step("biometrics", "Biometrics", "Attend the appointment with your passport.", {
            documents: ["Passport", "Appointment confirmation"],
            costGbp: 0,
            time: "1 day",
            whoCanHelp: "The visa application centre",
          }),
          step("decision", "Visa decision", "Travel only after the decision and the vignette or digital status are issued.", {
            documents: ["Decision letter"],
            costGbp: 0,
            time: "Usually a few weeks",
            whoCanHelp: "You",
          }),
        ],
      },
      {
        id: "global-talent",
        name: "Global Talent",
        alwaysPotential: true,
        skilledBands: ["tech", "health"],
        fitReason: "Exceptional promise or talent can be endorsed without a job offer. It depends on the strength of the professional record.",
        steps: [
          step("endorse", "Endorsement", "Prepare evidence of recognition in your field.", { time: "1–2 months", whoCanHelp: "An endorsing body" }),
        ],
      },
      {
        id: "student",
        name: "Student",
        alwaysPotential: true,
        fitReason: "A Student visa needs a place at a licensed sponsor and funds for the course.",
        steps: [step("cas", "Confirmation of Acceptance", "The school issues this after you accept a place.", { time: "1–3 months", whoCanHelp: "The school" })],
      },
      {
        id: "family",
        name: "Family",
        familyOnly: true,
        fitReason: "A partner who is British or settled can sponsor you. This does not apply to a single applicant.",
        steps: [step("partner", "Partner eligibility", "Check the partner's status and the income requirement.", { time: "1–2 weeks", whoCanHelp: "Your partner" })],
      },
    ],
    settlement: [
      { id: "brp", title: "Collect your status evidence", detail: "Save the decision email and any share code your employer will ask for." },
      { id: "bank", title: "Open a bank account", detail: "A passport and proof of address are the usual pair." },
      { id: "ni", title: "Apply for a National Insurance number", detail: "You can start work before it arrives." },
      { id: "gp", title: "Register with a GP", detail: "Healthcare is through the NHS once you are a resident." },
      { id: "sim", title: "Get a SIM", detail: "Needed for banking checks and most job applications." },
      { id: "housing", title: "Find permanent accommodation", detail: "Right-to-rent checks are standard. Bring the visa decision and a passport." },
      { id: "school", title: "Apply for a school place", detail: "Councils allocate places by address." },
      { id: "transport", title: "Set up local transport", detail: "Oyster or a regional pass, plus a railcard if you commute." },
    ],
    channels: ["Moving to the UK", "Skilled Worker", "Jobs", "Housing", "London", "Manchester", "Students", "Families", "New arrivals"],
  },
  {
    slug: "australia",
    name: "Australia",
    flag: "🇦🇺",
    climate: "warm",
    summary: "Skilled migration usually starts with a skills assessment, then an expression of interest.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: true,
    settlementBase: 76,
    prepMonths: 12,
    documentCount: 14,
    housingGbp: 1500,
    costs: { visa: 2200, flight: 980, deposit: 2600, rent: 1700, emergency: 3400, documents: 740, other: 2880 },
    jobStrength: { tech: "Strong", health: "Strong", education: "Moderate", other: "Moderate" },
    jobCount: { tech: 24, health: 33, education: 12, other: 9 },
    routes: [
      {
        id: "skilled",
        name: "Skilled migration",
        featured: true,
        skilledBands: ["tech", "health", "education"],
        minEducation: "bachelor",
        minExperience: 2,
        maxAge: 45,
        minEnglish: "intermediate",
        fitReason: "Points reward age, English, skilled work, and a positive skills assessment.",
        steps: [
          step("skills", "Skills assessment", "Have your occupation assessed by the authority for that job.", {
            documents: ["CV", "References", "Qualification"],
            costGbp: 450,
            time: "6–16 weeks",
            whoCanHelp: "The assessing authority for your occupation",
          }),
          step("english", "English test", "Book IELTS, PTE, or another accepted test.", {
            documents: ["Passport"],
            costGbp: 280,
            time: "2–4 weeks",
            whoCanHelp: "An approved test centre",
          }),
          step("eoi", "Expression of Interest", "Submit the EOI once points evidence is ready.", {
            documents: ["Skills result", "English result"],
            costGbp: 0,
            time: "1 week",
            whoCanHelp: "You",
          }),
          step("invite", "Invitation", "Invitations go to higher-scoring profiles first.", {
            time: "Often several months",
            whoCanHelp: "You",
          }),
          step("visa", "Visa application", "Lodge the visa with police checks and health examinations.", {
            documents: ["Police certificate", "Health exam", "Proof of funds"],
            costGbp: 2200,
            time: "Several months",
            whoCanHelp: "A registered migration agent",
          }),
          step("decision", "Visa decision", "Wait for the grant before you book a one-way move.", {
            time: "Several months",
            whoCanHelp: "You",
          }),
        ],
      },
      {
        id: "student",
        name: "Student",
        alwaysPotential: true,
        fitReason: "A student visa needs a course offer and funds for tuition and living costs.",
        steps: [step("offer", "Course offer", "Accept a place with a CRICOS-registered provider.", { time: "1–3 months", whoCanHelp: "The school" })],
      },
    ],
    settlement: [
      { id: "tfn", title: "Apply for a tax file number", detail: "Employers need it so you are not taxed at the highest rate." },
      { id: "bank", title: "Open a bank account", detail: "Passport and address evidence are enough at most banks." },
      { id: "medicare", title: "Enrol in Medicare if you are eligible", detail: "Permanent visa holders can enrol. Temporary visas vary." },
      { id: "sim", title: "Get a SIM", detail: "Needed for myGov and banking." },
      { id: "housing", title: "Find permanent accommodation", detail: "Rental applications ask for references and proof of income." },
      { id: "school", title: "Enrol children at school", detail: "Public schools enrol through the state education department." },
      { id: "licence", title: "Convert your driving licence", detail: "Each state sets its own exchange window." },
    ],
    channels: ["Moving to Australia", "Skilled migration", "Jobs", "Housing", "Sydney", "Melbourne", "Students", "Families"],
  },
  {
    slug: "netherlands",
    name: "Netherlands",
    flag: "🇳🇱",
    climate: "mild",
    summary: "The highly skilled migrant route is employer-led. English is widely used at work in tech.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: false,
    settlementBase: 77,
    prepMonths: 6,
    documentCount: 8,
    housingGbp: 1500,
    costs: { visa: 900, flight: 280, deposit: 2800, rent: 1600, emergency: 2800, documents: 360, other: 2060 },
    jobStrength: { tech: "Strong", health: "Moderate", education: "Limited", other: "Moderate" },
    jobCount: { tech: 22, health: 9, education: 4, other: 8 },
    routes: [
      {
        id: "hsm",
        name: "Highly skilled migrant",
        featured: true,
        needsSponsor: true,
        skilledBands: ["tech", "health"],
        minEducation: "bachelor",
        fitReason: "A recognised sponsor must offer a salary above the threshold for your age.",
        steps: [
          step("offer", "Sponsored offer", "The company has to be a recognised sponsor.", { time: "Varies", whoCanHelp: "The employer" }),
          step("permit", "Residence permit", "The employer often files this with you.", { costGbp: 350, time: "2–8 weeks", whoCanHelp: "The employer's HR team" }),
        ],
      },
      {
        id: "orientation",
        name: "Orientation year",
        alwaysPotential: true,
        minEducation: "master",
        fitReason: "Graduates of Dutch universities, and some highly ranked universities, can get a search year. It depends on the school.",
        steps: [step("graduate", "Confirm the degree qualifies", "Check whether your university is on the accepted list.", { time: "1 week", whoCanHelp: "The IND guidance" })],
      },
    ],
    settlement: [
      { id: "bsn", title: "Collect your BSN", detail: "Register in the personal records database at the municipality." },
      { id: "bank", title: "Open a bank account", detail: "A BSN makes this much easier." },
      { id: "health", title: "Buy Dutch health insurance", detail: "You generally have four months to take out basic cover." },
      { id: "sim", title: "Get a SIM", detail: "Use it to pass identity checks at the bank." },
      { id: "housing", title: "Find housing", detail: "The deposit is often one or two months. Housing is the tightest part of this move." },
      { id: "transport", title: "Get an OV-chipkaart", detail: "Trains and trams run on the national transit card." },
    ],
    channels: ["Moving to the Netherlands", "Highly skilled migrant", "Jobs", "Housing", "Amsterdam", "New arrivals"],
  },
  {
    slug: "ireland",
    name: "Ireland",
    flag: "🇮🇪",
    climate: "mild",
    summary: "Critical Skills roles, including much of tech and health, still need an Irish job offer.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: false,
    settlementBase: 75,
    prepMonths: 6,
    documentCount: 8,
    housingGbp: 1550,
    costs: { visa: 1100, flight: 320, deposit: 2600, rent: 1700, emergency: 2600, documents: 340, other: 2140 },
    jobStrength: { tech: "Strong", health: "Strong", education: "Moderate", other: "Limited" },
    jobCount: { tech: 19, health: 21, education: 7, other: 6 },
    routes: [
      {
        id: "critical-skills",
        name: "Critical Skills",
        featured: true,
        needsSponsor: true,
        skilledBands: ["tech", "health"],
        minEducation: "bachelor",
        fitReason: "The occupation list is generous for tech and health, but an Irish employer still has to hire you.",
        steps: [
          step("offer", "Job offer", "The role and salary need to match the Critical Skills rules.", { time: "Varies", whoCanHelp: "The employer" }),
          step("permit", "Employment permit", "The employer or you file the permit before the visa, if a visa is required.", { costGbp: 900, time: "6–12 weeks", whoCanHelp: "The employer" }),
        ],
      },
      {
        id: "student",
        name: "Student",
        alwaysPotential: true,
        fitReason: "A student route needs a course offer and evidence of fees and living costs.",
        steps: [step("course", "Course offer", "Accept a place and show you can pay.", { time: "1–3 months", whoCanHelp: "The college" })],
      },
    ],
    settlement: [
      { id: "pps", title: "Apply for a PPS number", detail: "You need it for tax and many public services." },
      { id: "bank", title: "Open a bank account", detail: "Bring your passport, permit, and proof of address." },
      { id: "gp", title: "Register with a GP", detail: "Ask the employer which insurance scheme they use." },
      { id: "sim", title: "Get a SIM", detail: "A local number speeds up banking." },
      { id: "housing", title: "Find housing", detail: "Start viewings early. Deposits and references are standard." },
      { id: "leap", title: "Get a Leap card", detail: "Buses, trams, and trains in Dublin use it." },
    ],
    channels: ["Moving to Ireland", "Critical Skills", "Jobs", "Housing", "Dublin", "New arrivals"],
  },
  {
    slug: "portugal",
    name: "Portugal",
    flag: "🇵🇹",
    climate: "warm",
    summary: "A lower move budget can go further here. Job-seeker and residence routes depend on the exact purpose.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: false,
    recommendLanguage: "Portuguese",
    settlementBase: 72,
    prepMonths: 6,
    documentCount: 9,
    housingGbp: 900,
    costs: { visa: 420, flight: 380, deposit: 1400, rent: 900, emergency: 2200, documents: 360, other: 1540 },
    jobStrength: { tech: "Moderate", health: "Moderate", education: "Limited", other: "Moderate" },
    jobCount: { tech: 14, health: 8, education: 3, other: 7 },
    routes: [
      {
        id: "job-seeker",
        name: "Job seeker",
        featured: true,
        minEducation: "bachelor",
        minEnglish: "intermediate",
        recommendLanguage: "Portuguese",
        fitReason: "A job-seeker stay can be used to look for work. It is not a grant of residence on its own.",
        steps: [
          step("purpose", "Confirm the purpose", "Decide whether you are seeking work, studying, or joining family.", { time: "1 week", whoCanHelp: "You" }),
          step("funds", "Show means of support", "Prepare savings evidence that covers the stay.", { documents: ["Bank statements"], time: "1 week", whoCanHelp: "Your bank" }),
          step("apply", "Visa application", "Book the appointment that covers where you live.", { costGbp: 420, time: "Several weeks", whoCanHelp: "The consulate" }),
        ],
      },
      {
        id: "student",
        name: "Student",
        alwaysPotential: true,
        fitReason: "A student visa needs admission and funds.",
        steps: [step("admit", "Admission", "Accept a place at a Portuguese institution.", { time: "1–3 months", whoCanHelp: "The university" })],
      },
    ],
    settlement: [
      { id: "nif", title: "Get a tax number (NIF)", detail: "You need it to rent, contract utilities, and open a bank account." },
      { id: "bank", title: "Open a bank account", detail: "The NIF and passport are the usual starting documents." },
      { id: "address", title: "Register your address", detail: "The parish council or tax office can record it, depending on your status." },
      { id: "health", title: "Arrange health cover", detail: "Private cover is often required at the visa stage. Public registration comes later." },
      { id: "sim", title: "Get a SIM", detail: "Needed for government appointments." },
      { id: "housing", title: "Find longer-term housing", detail: "Landlords often ask for a deposit and a NIF." },
      { id: "transport", title: "Get a transit card", detail: "Lisbon and Porto have monthly passes that are much cheaper than taxis." },
    ],
    channels: ["Moving to Portugal", "Job seeker", "Jobs", "Housing", "Lisbon", "Porto", "New arrivals"],
  },
  {
    slug: "united-arab-emirates",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    climate: "warm",
    summary: "Residence is tied to an employer, a business, or a property. There is no points-based skilled visa.",
    englishFriendly: true,
    englishAccepted: true,
    englishTestExpected: false,
    settlementBase: 70,
    prepMonths: 4,
    documentCount: 7,
    housingGbp: 1300,
    costs: { visa: 700, flight: 520, deposit: 2000, rent: 1400, emergency: 2200, documents: 280, other: 1700 },
    jobStrength: { tech: "Moderate", health: "Moderate", education: "Moderate", other: "Moderate" },
    jobCount: { tech: 17, health: 15, education: 11, other: 13 },
    routes: [
      {
        id: "employment",
        name: "Employment residence",
        featured: true,
        needsSponsor: true,
        fitReason: "An employer sponsors the residence visa. The offer comes before the visa.",
        steps: [
          step("offer", "Employment offer", "Confirm the company will sponsor residence, not only fly you in on a visit visa.", { time: "Varies", whoCanHelp: "The employer" }),
          step("entry", "Entry and medical", "Complete the medical and biometrics after you arrive, if that is how the employer files.", { costGbp: 250, time: "1–3 weeks", whoCanHelp: "The employer's PRO" }),
          step("eid", "Emirates ID", "Collect the ID once the residence visa is stamped.", { time: "1–2 weeks", whoCanHelp: "The employer" }),
        ],
      },
      {
        id: "student",
        name: "Student",
        alwaysPotential: true,
        fitReason: "Universities can sponsor a student residence visa.",
        steps: [step("admit", "Admission", "Accept a place with a university that will sponsor you.", { time: "1–3 months", whoCanHelp: "The university" })],
      },
    ],
    settlement: [
      { id: "eid", title: "Collect your Emirates ID", detail: "You need it for SIM cards, banking, and tenancy." },
      { id: "bank", title: "Open a bank account", detail: "Banks ask for the Emirates ID and a salary letter or tenancy." },
      { id: "sim", title: "Get a SIM", detail: "Registration is tied to your Emirates ID." },
      { id: "housing", title: "Sort housing", detail: "Many contracts include an allowance. Check whether the employer pays the deposit." },
      { id: "school", title: "Apply to schools", detail: "School places are private and should be budgeted separately." },
      { id: "transport", title: "Plan transport", detail: "Metro and ride-hailing cover a lot of Dubai. Other emirates differ." },
    ],
    channels: ["Moving to the UAE", "Employment visas", "Jobs", "Housing", "Dubai", "Abu Dhabi", "Families"],
  },
]

export function listDestinations(): Destination[] {
  return DESTINATIONS
}

export function getDestination(slug: string): Destination | undefined {
  return DESTINATIONS.find((destination) => destination.slug === slug)
}

export const CITIZENSHIPS = [
  "Nigeria",
  "Ghana",
  "Kenya",
  "South Africa",
  "United Kingdom",
  "India",
  "Philippines",
  "United States",
  "Canada",
  "Germany",
  "France",
  "United Arab Emirates",
] as const

export const LANGUAGE_OPTIONS = ["English", "French", "German", "Arabic", "Portuguese", "Spanish", "Yoruba", "Swahili"] as const

export const MARKETPLACE = [
  { id: "lawyers", title: "Immigration lawyers", detail: "Regulated advice on the route you actually qualify for." },
  { id: "visa", title: "Visa specialists", detail: "Form filling, appointments, and document checks." },
  { id: "movers", title: "Movers", detail: "Sea and air freight for a household, not a suitcase." },
  { id: "flights", title: "Flights", detail: "One-way fares timed to a visa decision, not a holiday." },
  { id: "temporary", title: "Temporary accommodation", detail: "A landing place for the first weeks." },
  { id: "housing", title: "Permanent housing", detail: "Rentals that accept newcomers without a local credit file." },
  { id: "insurance", title: "Insurance", detail: "Health cover for the gap before local insurance starts." },
  { id: "sim", title: "SIM and eSIM", detail: "A number that works the day you land." },
  { id: "banking", title: "International banking", detail: "An account you can open before payroll starts." },
  { id: "fx", title: "Currency exchange", detail: "Move the relocation fund without a tourist rate." },
  { id: "tax", title: "Tax advisers", detail: "When you stop being tax-resident at home and start being resident abroad." },
  { id: "translation", title: "Document translation", detail: "Certified translations of degrees, birth certificates, and police checks." },
  { id: "credentials", title: "Credential evaluation", detail: "The assessment a skilled route asks for before you apply." },
  { id: "language", title: "Language lessons", detail: "The test or the everyday language the destination recommends." },
  { id: "schools", title: "Schools", detail: "Places for children, including what to bring to enrolment." },
  { id: "transfers", title: "Airport transfers", detail: "The first ride, booked before you land." },
  { id: "storage", title: "Storage", detail: "Leave what should not fly with you." },
] as const

export const PASSPORT_ITEMS = [
  { id: "identity", group: "Identity", title: "Legal name and date of birth" },
  { id: "passport", group: "Identity", title: "Passport" },
  { id: "education", group: "Education", title: "Degrees and transcripts" },
  { id: "employment", group: "Employment", title: "Employment history" },
  { id: "qualifications", group: "Employment", title: "Professional qualifications" },
  { id: "languages", group: "Evidence", title: "Language tests" },
  { id: "police", group: "Evidence", title: "Police certificates" },
  { id: "visas", group: "Evidence", title: "Previous visas" },
  { id: "dependants", group: "Family", title: "Dependants" },
  { id: "funds", group: "Evidence", title: "Financial evidence" },
  { id: "references", group: "Employment", title: "References" },
] as const

export const EXAMPLE_MENTORS = [
  {
    name: "Chidi",
    from: "Nigeria",
    to: "Germany",
    role: "Software engineer",
    year: 2025,
    helped: 312,
    focus: "Opportunity Card and a first job in Berlin",
  },
  {
    name: "Amina",
    from: "Kenya",
    to: "Canada",
    role: "Nurse",
    year: 2024,
    helped: 186,
    focus: "Credential assessment and provincial licensing",
  },
  {
    name: "Ade",
    from: "Nigeria",
    to: "United Kingdom",
    role: "Cybersecurity analyst",
    year: 2025,
    helped: 94,
    focus: "Finding a sponsor and the Skilled Worker file",
  },
] as const
