/** Exhaustive country lists for EasyMove Score (AI-backed; not limited to catalog destinations). */

export type CountryOption = {
  slug: string
  name: string
}

function slugify(name: string) {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
}

const COUNTRY_NAMES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const

/** Prefer catalog-compatible slugs where EasyMove already has deep destination pages. */
const SLUG_OVERRIDES: Record<string, string> = {
  "United Kingdom": "united-kingdom",
  "United Arab Emirates": "united-arab-emirates",
  "United States": "united-states",
  "South Korea": "south-korea",
  "North Korea": "north-korea",
  "South Africa": "south-africa",
  "South Sudan": "south-sudan",
  "New Zealand": "new-zealand",
  "Saudi Arabia": "saudi-arabia",
  "Czechia": "czechia",
  "Ivory Coast": "ivory-coast",
  "Democratic Republic of the Congo": "democratic-republic-of-the-congo",
  "Central African Republic": "central-african-republic",
  "Bosnia and Herzegovina": "bosnia-and-herzegovina",
  "Antigua and Barbuda": "antigua-and-barbuda",
  "Trinidad and Tobago": "trinidad-and-tobago",
  "Papua New Guinea": "papua-new-guinea",
  "North Macedonia": "north-macedonia",
  "Hong Kong": "hong-kong",
  "Vatican City": "vatican-city",
  "Sao Tome and Principe": "sao-tome-and-principe",
  "Saint Kitts and Nevis": "saint-kitts-and-nevis",
  "Saint Vincent and the Grenadines": "saint-vincent-and-the-grenadines",
  "Solomon Islands": "solomon-islands",
  "Marshall Islands": "marshall-islands",
  "Cabo Verde": "cabo-verde",
  "Timor-Leste": "timor-leste",
}

export const WORLD_COUNTRIES: CountryOption[] = COUNTRY_NAMES.map((name) => ({
  name,
  slug: SLUG_OVERRIDES[name] ?? slugify(name),
}))

export const WORLD_COUNTRY_NAMES = WORLD_COUNTRIES.map((c) => c.name)

export function getCountryBySlug(slug: string): CountryOption | undefined {
  return WORLD_COUNTRIES.find((c) => c.slug === slug)
}

export function getCountryByName(name: string): CountryOption | undefined {
  const needle = name.trim().toLowerCase()
  return WORLD_COUNTRIES.find((c) => c.name.toLowerCase() === needle)
}
